/*
Game Aggregator API Documentation

Testing FreespinsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package gamehubapi

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_gamehubapi_FreespinsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FreespinsAPIService CancelAStandaloneFreespin", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var freespinId string

		resp, httpRes, err := apiClient.FreespinsAPI.CancelAStandaloneFreespin(context.Background(), freespinId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FreespinsAPIService CreateAStandaloneFreespin", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.FreespinsAPI.CreateAStandaloneFreespin(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
