/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetMultiSessionStatus200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMultiSessionStatus200Response{}

// GetMultiSessionStatus200Response struct for GetMultiSessionStatus200Response
type GetMultiSessionStatus200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *GetMultiSessionStatus200ResponseData `json:"data,omitempty"`
}

// NewGetMultiSessionStatus200Response instantiates a new GetMultiSessionStatus200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMultiSessionStatus200Response() *GetMultiSessionStatus200Response {
	this := GetMultiSessionStatus200Response{}
	return &this
}

// NewGetMultiSessionStatus200ResponseWithDefaults instantiates a new GetMultiSessionStatus200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMultiSessionStatus200ResponseWithDefaults() *GetMultiSessionStatus200Response {
	this := GetMultiSessionStatus200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetMultiSessionStatus200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMultiSessionStatus200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetMultiSessionStatus200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetMultiSessionStatus200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetMultiSessionStatus200Response) GetData() GetMultiSessionStatus200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GetMultiSessionStatus200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMultiSessionStatus200Response) GetDataOk() (*GetMultiSessionStatus200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetMultiSessionStatus200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetMultiSessionStatus200ResponseData and assigns it to the Data field.
func (o *GetMultiSessionStatus200Response) SetData(v GetMultiSessionStatus200ResponseData) {
	o.Data = &v
}

func (o GetMultiSessionStatus200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMultiSessionStatus200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetMultiSessionStatus200Response struct {
	value *GetMultiSessionStatus200Response
	isSet bool
}

func (v NullableGetMultiSessionStatus200Response) Get() *GetMultiSessionStatus200Response {
	return v.value
}

func (v *NullableGetMultiSessionStatus200Response) Set(val *GetMultiSessionStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMultiSessionStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMultiSessionStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMultiSessionStatus200Response(val *GetMultiSessionStatus200Response) *NullableGetMultiSessionStatus200Response {
	return &NullableGetMultiSessionStatus200Response{value: val, isSet: true}
}

func (v NullableGetMultiSessionStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMultiSessionStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


