/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkCreateExternalGamesFromJSONArrayRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkCreateExternalGamesFromJSONArrayRequest{}

// BulkCreateExternalGamesFromJSONArrayRequest struct for BulkCreateExternalGamesFromJSONArrayRequest
type BulkCreateExternalGamesFromJSONArrayRequest struct {
	// Must have at least 1 items. Must not have more than 1000 items.
	Games []CreateASingleExternalGameRequest `json:"games"`
}

type _BulkCreateExternalGamesFromJSONArrayRequest BulkCreateExternalGamesFromJSONArrayRequest

// NewBulkCreateExternalGamesFromJSONArrayRequest instantiates a new BulkCreateExternalGamesFromJSONArrayRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreateExternalGamesFromJSONArrayRequest(games []CreateASingleExternalGameRequest) *BulkCreateExternalGamesFromJSONArrayRequest {
	this := BulkCreateExternalGamesFromJSONArrayRequest{}
	this.Games = games
	return &this
}

// NewBulkCreateExternalGamesFromJSONArrayRequestWithDefaults instantiates a new BulkCreateExternalGamesFromJSONArrayRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreateExternalGamesFromJSONArrayRequestWithDefaults() *BulkCreateExternalGamesFromJSONArrayRequest {
	this := BulkCreateExternalGamesFromJSONArrayRequest{}
	return &this
}

// GetGames returns the Games field value
func (o *BulkCreateExternalGamesFromJSONArrayRequest) GetGames() []CreateASingleExternalGameRequest {
	if o == nil {
		var ret []CreateASingleExternalGameRequest
		return ret
	}

	return o.Games
}

// GetGamesOk returns a tuple with the Games field value
// and a boolean to check if the value has been set.
func (o *BulkCreateExternalGamesFromJSONArrayRequest) GetGamesOk() ([]CreateASingleExternalGameRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Games, true
}

// SetGames sets field value
func (o *BulkCreateExternalGamesFromJSONArrayRequest) SetGames(v []CreateASingleExternalGameRequest) {
	o.Games = v
}

func (o BulkCreateExternalGamesFromJSONArrayRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkCreateExternalGamesFromJSONArrayRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["games"] = o.Games
	return toSerialize, nil
}

func (o *BulkCreateExternalGamesFromJSONArrayRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"games",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkCreateExternalGamesFromJSONArrayRequest := _BulkCreateExternalGamesFromJSONArrayRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkCreateExternalGamesFromJSONArrayRequest)

	if err != nil {
		return err
	}

	*o = BulkCreateExternalGamesFromJSONArrayRequest(varBulkCreateExternalGamesFromJSONArrayRequest)

	return err
}

type NullableBulkCreateExternalGamesFromJSONArrayRequest struct {
	value *BulkCreateExternalGamesFromJSONArrayRequest
	isSet bool
}

func (v NullableBulkCreateExternalGamesFromJSONArrayRequest) Get() *BulkCreateExternalGamesFromJSONArrayRequest {
	return v.value
}

func (v *NullableBulkCreateExternalGamesFromJSONArrayRequest) Set(val *BulkCreateExternalGamesFromJSONArrayRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreateExternalGamesFromJSONArrayRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreateExternalGamesFromJSONArrayRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreateExternalGamesFromJSONArrayRequest(val *BulkCreateExternalGamesFromJSONArrayRequest) *NullableBulkCreateExternalGamesFromJSONArrayRequest {
	return &NullableBulkCreateExternalGamesFromJSONArrayRequest{value: val, isSet: true}
}

func (v NullableBulkCreateExternalGamesFromJSONArrayRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreateExternalGamesFromJSONArrayRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


