/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetApiV1Producers401Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiV1Producers401Response{}

// GetApiV1Producers401Response struct for GetApiV1Producers401Response
type GetApiV1Producers401Response struct {
	Error *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Code *int32 `json:"code,omitempty"`
}

// NewGetApiV1Producers401Response instantiates a new GetApiV1Producers401Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiV1Producers401Response() *GetApiV1Producers401Response {
	this := GetApiV1Producers401Response{}
	return &this
}

// NewGetApiV1Producers401ResponseWithDefaults instantiates a new GetApiV1Producers401Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiV1Producers401ResponseWithDefaults() *GetApiV1Producers401Response {
	this := GetApiV1Producers401Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetApiV1Producers401Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1Producers401Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetApiV1Producers401Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetApiV1Producers401Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetApiV1Producers401Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1Producers401Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetApiV1Producers401Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetApiV1Producers401Response) SetMessage(v string) {
	o.Message = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetApiV1Producers401Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1Producers401Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetApiV1Producers401Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *GetApiV1Producers401Response) SetCode(v int32) {
	o.Code = &v
}

func (o GetApiV1Producers401Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiV1Producers401Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableGetApiV1Producers401Response struct {
	value *GetApiV1Producers401Response
	isSet bool
}

func (v NullableGetApiV1Producers401Response) Get() *GetApiV1Producers401Response {
	return v.value
}

func (v *NullableGetApiV1Producers401Response) Set(val *GetApiV1Producers401Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiV1Producers401Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiV1Producers401Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiV1Producers401Response(val *GetApiV1Producers401Response) *NullableGetApiV1Producers401Response {
	return &NullableGetApiV1Producers401Response{value: val, isSet: true}
}

func (v NullableGetApiV1Producers401Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiV1Producers401Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


