/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the CancelAStandaloneFreespin200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelAStandaloneFreespin200ResponseData{}

// CancelAStandaloneFreespin200ResponseData struct for CancelAStandaloneFreespin200ResponseData
type CancelAStandaloneFreespin200ResponseData struct {
	FreespinId *string `json:"freespin_id,omitempty"`
	Status *string `json:"status,omitempty"`
	CancelledAt *string `json:"cancelled_at,omitempty"`
	RemainingCount *int32 `json:"remaining_count,omitempty"`
	UsedCount *int32 `json:"used_count,omitempty"`
}

// NewCancelAStandaloneFreespin200ResponseData instantiates a new CancelAStandaloneFreespin200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelAStandaloneFreespin200ResponseData() *CancelAStandaloneFreespin200ResponseData {
	this := CancelAStandaloneFreespin200ResponseData{}
	return &this
}

// NewCancelAStandaloneFreespin200ResponseDataWithDefaults instantiates a new CancelAStandaloneFreespin200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelAStandaloneFreespin200ResponseDataWithDefaults() *CancelAStandaloneFreespin200ResponseData {
	this := CancelAStandaloneFreespin200ResponseData{}
	return &this
}

// GetFreespinId returns the FreespinId field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200ResponseData) GetFreespinId() string {
	if o == nil || IsNil(o.FreespinId) {
		var ret string
		return ret
	}
	return *o.FreespinId
}

// GetFreespinIdOk returns a tuple with the FreespinId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200ResponseData) GetFreespinIdOk() (*string, bool) {
	if o == nil || IsNil(o.FreespinId) {
		return nil, false
	}
	return o.FreespinId, true
}

// HasFreespinId returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200ResponseData) HasFreespinId() bool {
	if o != nil && !IsNil(o.FreespinId) {
		return true
	}

	return false
}

// SetFreespinId gets a reference to the given string and assigns it to the FreespinId field.
func (o *CancelAStandaloneFreespin200ResponseData) SetFreespinId(v string) {
	o.FreespinId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200ResponseData) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200ResponseData) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200ResponseData) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CancelAStandaloneFreespin200ResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetCancelledAt returns the CancelledAt field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200ResponseData) GetCancelledAt() string {
	if o == nil || IsNil(o.CancelledAt) {
		var ret string
		return ret
	}
	return *o.CancelledAt
}

// GetCancelledAtOk returns a tuple with the CancelledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200ResponseData) GetCancelledAtOk() (*string, bool) {
	if o == nil || IsNil(o.CancelledAt) {
		return nil, false
	}
	return o.CancelledAt, true
}

// HasCancelledAt returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200ResponseData) HasCancelledAt() bool {
	if o != nil && !IsNil(o.CancelledAt) {
		return true
	}

	return false
}

// SetCancelledAt gets a reference to the given string and assigns it to the CancelledAt field.
func (o *CancelAStandaloneFreespin200ResponseData) SetCancelledAt(v string) {
	o.CancelledAt = &v
}

// GetRemainingCount returns the RemainingCount field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200ResponseData) GetRemainingCount() int32 {
	if o == nil || IsNil(o.RemainingCount) {
		var ret int32
		return ret
	}
	return *o.RemainingCount
}

// GetRemainingCountOk returns a tuple with the RemainingCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200ResponseData) GetRemainingCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RemainingCount) {
		return nil, false
	}
	return o.RemainingCount, true
}

// HasRemainingCount returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200ResponseData) HasRemainingCount() bool {
	if o != nil && !IsNil(o.RemainingCount) {
		return true
	}

	return false
}

// SetRemainingCount gets a reference to the given int32 and assigns it to the RemainingCount field.
func (o *CancelAStandaloneFreespin200ResponseData) SetRemainingCount(v int32) {
	o.RemainingCount = &v
}

// GetUsedCount returns the UsedCount field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200ResponseData) GetUsedCount() int32 {
	if o == nil || IsNil(o.UsedCount) {
		var ret int32
		return ret
	}
	return *o.UsedCount
}

// GetUsedCountOk returns a tuple with the UsedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200ResponseData) GetUsedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.UsedCount) {
		return nil, false
	}
	return o.UsedCount, true
}

// HasUsedCount returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200ResponseData) HasUsedCount() bool {
	if o != nil && !IsNil(o.UsedCount) {
		return true
	}

	return false
}

// SetUsedCount gets a reference to the given int32 and assigns it to the UsedCount field.
func (o *CancelAStandaloneFreespin200ResponseData) SetUsedCount(v int32) {
	o.UsedCount = &v
}

func (o CancelAStandaloneFreespin200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelAStandaloneFreespin200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FreespinId) {
		toSerialize["freespin_id"] = o.FreespinId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CancelledAt) {
		toSerialize["cancelled_at"] = o.CancelledAt
	}
	if !IsNil(o.RemainingCount) {
		toSerialize["remaining_count"] = o.RemainingCount
	}
	if !IsNil(o.UsedCount) {
		toSerialize["used_count"] = o.UsedCount
	}
	return toSerialize, nil
}

type NullableCancelAStandaloneFreespin200ResponseData struct {
	value *CancelAStandaloneFreespin200ResponseData
	isSet bool
}

func (v NullableCancelAStandaloneFreespin200ResponseData) Get() *CancelAStandaloneFreespin200ResponseData {
	return v.value
}

func (v *NullableCancelAStandaloneFreespin200ResponseData) Set(val *CancelAStandaloneFreespin200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelAStandaloneFreespin200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelAStandaloneFreespin200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelAStandaloneFreespin200ResponseData(val *CancelAStandaloneFreespin200ResponseData) *NullableCancelAStandaloneFreespin200ResponseData {
	return &NullableCancelAStandaloneFreespin200ResponseData{value: val, isSet: true}
}

func (v NullableCancelAStandaloneFreespin200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelAStandaloneFreespin200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


