/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the RevokeAToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeAToken200Response{}

// RevokeAToken200Response struct for RevokeAToken200Response
type RevokeAToken200Response struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewRevokeAToken200Response instantiates a new RevokeAToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeAToken200Response() *RevokeAToken200Response {
	this := RevokeAToken200Response{}
	return &this
}

// NewRevokeAToken200ResponseWithDefaults instantiates a new RevokeAToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeAToken200ResponseWithDefaults() *RevokeAToken200Response {
	this := RevokeAToken200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *RevokeAToken200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeAToken200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *RevokeAToken200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *RevokeAToken200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RevokeAToken200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RevokeAToken200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RevokeAToken200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RevokeAToken200Response) SetMessage(v string) {
	o.Message = &v
}

func (o RevokeAToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeAToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableRevokeAToken200Response struct {
	value *RevokeAToken200Response
	isSet bool
}

func (v NullableRevokeAToken200Response) Get() *RevokeAToken200Response {
	return v.value
}

func (v *NullableRevokeAToken200Response) Set(val *RevokeAToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeAToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeAToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeAToken200Response(val *RevokeAToken200Response) *NullableRevokeAToken200Response {
	return &NullableRevokeAToken200Response{value: val, isSet: true}
}

func (v NullableRevokeAToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeAToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


