/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetTransactionHistory200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTransactionHistory200ResponseDataInner{}

// GetTransactionHistory200ResponseDataInner struct for GetTransactionHistory200ResponseDataInner
type GetTransactionHistory200ResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	PlayerId *string `json:"player_id,omitempty"`
	Game *GetSessionStatus200ResponseDataGame `json:"game,omitempty"`
	Type *string `json:"type,omitempty"`
	Amount *float32 `json:"amount,omitempty"`
	Currency *string `json:"currency,omitempty"`
	BalanceAfter *float32 `json:"balance_after,omitempty"`
	RoundId *string `json:"round_id,omitempty"`
	Status *string `json:"status,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// NewGetTransactionHistory200ResponseDataInner instantiates a new GetTransactionHistory200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTransactionHistory200ResponseDataInner() *GetTransactionHistory200ResponseDataInner {
	this := GetTransactionHistory200ResponseDataInner{}
	return &this
}

// NewGetTransactionHistory200ResponseDataInnerWithDefaults instantiates a new GetTransactionHistory200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTransactionHistory200ResponseDataInnerWithDefaults() *GetTransactionHistory200ResponseDataInner {
	this := GetTransactionHistory200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetTransactionHistory200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetPlayerId returns the PlayerId field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetPlayerId() string {
	if o == nil || IsNil(o.PlayerId) {
		var ret string
		return ret
	}
	return *o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetPlayerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlayerId) {
		return nil, false
	}
	return o.PlayerId, true
}

// HasPlayerId returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasPlayerId() bool {
	if o != nil && !IsNil(o.PlayerId) {
		return true
	}

	return false
}

// SetPlayerId gets a reference to the given string and assigns it to the PlayerId field.
func (o *GetTransactionHistory200ResponseDataInner) SetPlayerId(v string) {
	o.PlayerId = &v
}

// GetGame returns the Game field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetGame() GetSessionStatus200ResponseDataGame {
	if o == nil || IsNil(o.Game) {
		var ret GetSessionStatus200ResponseDataGame
		return ret
	}
	return *o.Game
}

// GetGameOk returns a tuple with the Game field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetGameOk() (*GetSessionStatus200ResponseDataGame, bool) {
	if o == nil || IsNil(o.Game) {
		return nil, false
	}
	return o.Game, true
}

// HasGame returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasGame() bool {
	if o != nil && !IsNil(o.Game) {
		return true
	}

	return false
}

// SetGame gets a reference to the given GetSessionStatus200ResponseDataGame and assigns it to the Game field.
func (o *GetTransactionHistory200ResponseDataInner) SetGame(v GetSessionStatus200ResponseDataGame) {
	o.Game = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetTransactionHistory200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetAmount() float32 {
	if o == nil || IsNil(o.Amount) {
		var ret float32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetAmountOk() (*float32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given float32 and assigns it to the Amount field.
func (o *GetTransactionHistory200ResponseDataInner) SetAmount(v float32) {
	o.Amount = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetTransactionHistory200ResponseDataInner) SetCurrency(v string) {
	o.Currency = &v
}

// GetBalanceAfter returns the BalanceAfter field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetBalanceAfter() float32 {
	if o == nil || IsNil(o.BalanceAfter) {
		var ret float32
		return ret
	}
	return *o.BalanceAfter
}

// GetBalanceAfterOk returns a tuple with the BalanceAfter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetBalanceAfterOk() (*float32, bool) {
	if o == nil || IsNil(o.BalanceAfter) {
		return nil, false
	}
	return o.BalanceAfter, true
}

// HasBalanceAfter returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasBalanceAfter() bool {
	if o != nil && !IsNil(o.BalanceAfter) {
		return true
	}

	return false
}

// SetBalanceAfter gets a reference to the given float32 and assigns it to the BalanceAfter field.
func (o *GetTransactionHistory200ResponseDataInner) SetBalanceAfter(v float32) {
	o.BalanceAfter = &v
}

// GetRoundId returns the RoundId field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetRoundId() string {
	if o == nil || IsNil(o.RoundId) {
		var ret string
		return ret
	}
	return *o.RoundId
}

// GetRoundIdOk returns a tuple with the RoundId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetRoundIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoundId) {
		return nil, false
	}
	return o.RoundId, true
}

// HasRoundId returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasRoundId() bool {
	if o != nil && !IsNil(o.RoundId) {
		return true
	}

	return false
}

// SetRoundId gets a reference to the given string and assigns it to the RoundId field.
func (o *GetTransactionHistory200ResponseDataInner) SetRoundId(v string) {
	o.RoundId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetTransactionHistory200ResponseDataInner) SetStatus(v string) {
	o.Status = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetTransactionHistory200ResponseDataInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetTransactionHistory200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetTransactionHistory200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o GetTransactionHistory200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTransactionHistory200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.PlayerId) {
		toSerialize["player_id"] = o.PlayerId
	}
	if !IsNil(o.Game) {
		toSerialize["game"] = o.Game
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.BalanceAfter) {
		toSerialize["balance_after"] = o.BalanceAfter
	}
	if !IsNil(o.RoundId) {
		toSerialize["round_id"] = o.RoundId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableGetTransactionHistory200ResponseDataInner struct {
	value *GetTransactionHistory200ResponseDataInner
	isSet bool
}

func (v NullableGetTransactionHistory200ResponseDataInner) Get() *GetTransactionHistory200ResponseDataInner {
	return v.value
}

func (v *NullableGetTransactionHistory200ResponseDataInner) Set(val *GetTransactionHistory200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransactionHistory200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransactionHistory200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransactionHistory200ResponseDataInner(val *GetTransactionHistory200ResponseDataInner) *NullableGetTransactionHistory200ResponseDataInner {
	return &NullableGetTransactionHistory200ResponseDataInner{value: val, isSet: true}
}

func (v NullableGetTransactionHistory200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransactionHistory200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


