/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListWidgetTokens200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWidgetTokens200Response{}

// ListWidgetTokens200Response struct for ListWidgetTokens200Response
type ListWidgetTokens200Response struct {
	Success *bool `json:"success,omitempty"`
	Data []ListWidgetTokens200ResponseDataInner `json:"data,omitempty"`
}

// NewListWidgetTokens200Response instantiates a new ListWidgetTokens200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWidgetTokens200Response() *ListWidgetTokens200Response {
	this := ListWidgetTokens200Response{}
	return &this
}

// NewListWidgetTokens200ResponseWithDefaults instantiates a new ListWidgetTokens200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWidgetTokens200ResponseWithDefaults() *ListWidgetTokens200Response {
	this := ListWidgetTokens200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ListWidgetTokens200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ListWidgetTokens200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ListWidgetTokens200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListWidgetTokens200Response) GetData() []ListWidgetTokens200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []ListWidgetTokens200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200Response) GetDataOk() ([]ListWidgetTokens200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListWidgetTokens200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ListWidgetTokens200ResponseDataInner and assigns it to the Data field.
func (o *ListWidgetTokens200Response) SetData(v []ListWidgetTokens200ResponseDataInner) {
	o.Data = v
}

func (o ListWidgetTokens200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWidgetTokens200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableListWidgetTokens200Response struct {
	value *ListWidgetTokens200Response
	isSet bool
}

func (v NullableListWidgetTokens200Response) Get() *ListWidgetTokens200Response {
	return v.value
}

func (v *NullableListWidgetTokens200Response) Set(val *ListWidgetTokens200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListWidgetTokens200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListWidgetTokens200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWidgetTokens200Response(val *ListWidgetTokens200Response) *NullableListWidgetTokens200Response {
	return &NullableListWidgetTokens200Response{value: val, isSet: true}
}

func (v NullableListWidgetTokens200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWidgetTokens200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


