/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the CancelAStandaloneFreespin200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelAStandaloneFreespin200Response{}

// CancelAStandaloneFreespin200Response struct for CancelAStandaloneFreespin200Response
type CancelAStandaloneFreespin200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *CancelAStandaloneFreespin200ResponseData `json:"data,omitempty"`
}

// NewCancelAStandaloneFreespin200Response instantiates a new CancelAStandaloneFreespin200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelAStandaloneFreespin200Response() *CancelAStandaloneFreespin200Response {
	this := CancelAStandaloneFreespin200Response{}
	return &this
}

// NewCancelAStandaloneFreespin200ResponseWithDefaults instantiates a new CancelAStandaloneFreespin200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelAStandaloneFreespin200ResponseWithDefaults() *CancelAStandaloneFreespin200Response {
	this := CancelAStandaloneFreespin200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CancelAStandaloneFreespin200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin200Response) GetData() CancelAStandaloneFreespin200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret CancelAStandaloneFreespin200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin200Response) GetDataOk() (*CancelAStandaloneFreespin200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CancelAStandaloneFreespin200ResponseData and assigns it to the Data field.
func (o *CancelAStandaloneFreespin200Response) SetData(v CancelAStandaloneFreespin200ResponseData) {
	o.Data = &v
}

func (o CancelAStandaloneFreespin200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelAStandaloneFreespin200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCancelAStandaloneFreespin200Response struct {
	value *CancelAStandaloneFreespin200Response
	isSet bool
}

func (v NullableCancelAStandaloneFreespin200Response) Get() *CancelAStandaloneFreespin200Response {
	return v.value
}

func (v *NullableCancelAStandaloneFreespin200Response) Set(val *CancelAStandaloneFreespin200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelAStandaloneFreespin200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelAStandaloneFreespin200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelAStandaloneFreespin200Response(val *CancelAStandaloneFreespin200Response) *NullableCancelAStandaloneFreespin200Response {
	return &NullableCancelAStandaloneFreespin200Response{value: val, isSet: true}
}

func (v NullableCancelAStandaloneFreespin200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelAStandaloneFreespin200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


