/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the RegenerateDomainToken200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegenerateDomainToken200Response{}

// RegenerateDomainToken200Response struct for RegenerateDomainToken200Response
type RegenerateDomainToken200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *RegenerateDomainToken200ResponseData `json:"data,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewRegenerateDomainToken200Response instantiates a new RegenerateDomainToken200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegenerateDomainToken200Response() *RegenerateDomainToken200Response {
	this := RegenerateDomainToken200Response{}
	return &this
}

// NewRegenerateDomainToken200ResponseWithDefaults instantiates a new RegenerateDomainToken200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegenerateDomainToken200ResponseWithDefaults() *RegenerateDomainToken200Response {
	this := RegenerateDomainToken200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *RegenerateDomainToken200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegenerateDomainToken200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *RegenerateDomainToken200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *RegenerateDomainToken200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *RegenerateDomainToken200Response) GetData() RegenerateDomainToken200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret RegenerateDomainToken200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegenerateDomainToken200Response) GetDataOk() (*RegenerateDomainToken200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *RegenerateDomainToken200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given RegenerateDomainToken200ResponseData and assigns it to the Data field.
func (o *RegenerateDomainToken200Response) SetData(v RegenerateDomainToken200ResponseData) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *RegenerateDomainToken200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegenerateDomainToken200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *RegenerateDomainToken200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *RegenerateDomainToken200Response) SetMessage(v string) {
	o.Message = &v
}

func (o RegenerateDomainToken200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegenerateDomainToken200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableRegenerateDomainToken200Response struct {
	value *RegenerateDomainToken200Response
	isSet bool
}

func (v NullableRegenerateDomainToken200Response) Get() *RegenerateDomainToken200Response {
	return v.value
}

func (v *NullableRegenerateDomainToken200Response) Set(val *RegenerateDomainToken200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableRegenerateDomainToken200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableRegenerateDomainToken200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegenerateDomainToken200Response(val *RegenerateDomainToken200Response) *NullableRegenerateDomainToken200Response {
	return &NullableRegenerateDomainToken200Response{value: val, isSet: true}
}

func (v NullableRegenerateDomainToken200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegenerateDomainToken200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


