/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetTokenDetails200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTokenDetails200ResponseData{}

// GetTokenDetails200ResponseData struct for GetTokenDetails200ResponseData
type GetTokenDetails200ResponseData struct {
	Id *int32 `json:"id,omitempty"`
	Domain *string `json:"domain,omitempty"`
	WidgetType *string `json:"widget_type,omitempty"`
	PlayerId *string `json:"player_id,omitempty"`
	Currency *string `json:"currency,omitempty"`
	AllowedPoolTypes []string `json:"allowed_pool_types,omitempty"`
	Configuration *string `json:"configuration,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	IsValid *bool `json:"is_valid,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
	RequestCount *int32 `json:"request_count,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// NewGetTokenDetails200ResponseData instantiates a new GetTokenDetails200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTokenDetails200ResponseData() *GetTokenDetails200ResponseData {
	this := GetTokenDetails200ResponseData{}
	return &this
}

// NewGetTokenDetails200ResponseDataWithDefaults instantiates a new GetTokenDetails200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTokenDetails200ResponseDataWithDefaults() *GetTokenDetails200ResponseData {
	this := GetTokenDetails200ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetTokenDetails200ResponseData) SetId(v int32) {
	o.Id = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *GetTokenDetails200ResponseData) SetDomain(v string) {
	o.Domain = &v
}

// GetWidgetType returns the WidgetType field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetWidgetType() string {
	if o == nil || IsNil(o.WidgetType) {
		var ret string
		return ret
	}
	return *o.WidgetType
}

// GetWidgetTypeOk returns a tuple with the WidgetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetWidgetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WidgetType) {
		return nil, false
	}
	return o.WidgetType, true
}

// HasWidgetType returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasWidgetType() bool {
	if o != nil && !IsNil(o.WidgetType) {
		return true
	}

	return false
}

// SetWidgetType gets a reference to the given string and assigns it to the WidgetType field.
func (o *GetTokenDetails200ResponseData) SetWidgetType(v string) {
	o.WidgetType = &v
}

// GetPlayerId returns the PlayerId field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetPlayerId() string {
	if o == nil || IsNil(o.PlayerId) {
		var ret string
		return ret
	}
	return *o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetPlayerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlayerId) {
		return nil, false
	}
	return o.PlayerId, true
}

// HasPlayerId returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasPlayerId() bool {
	if o != nil && !IsNil(o.PlayerId) {
		return true
	}

	return false
}

// SetPlayerId gets a reference to the given string and assigns it to the PlayerId field.
func (o *GetTokenDetails200ResponseData) SetPlayerId(v string) {
	o.PlayerId = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *GetTokenDetails200ResponseData) SetCurrency(v string) {
	o.Currency = &v
}

// GetAllowedPoolTypes returns the AllowedPoolTypes field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetAllowedPoolTypes() []string {
	if o == nil || IsNil(o.AllowedPoolTypes) {
		var ret []string
		return ret
	}
	return o.AllowedPoolTypes
}

// GetAllowedPoolTypesOk returns a tuple with the AllowedPoolTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetAllowedPoolTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedPoolTypes) {
		return nil, false
	}
	return o.AllowedPoolTypes, true
}

// HasAllowedPoolTypes returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasAllowedPoolTypes() bool {
	if o != nil && !IsNil(o.AllowedPoolTypes) {
		return true
	}

	return false
}

// SetAllowedPoolTypes gets a reference to the given []string and assigns it to the AllowedPoolTypes field.
func (o *GetTokenDetails200ResponseData) SetAllowedPoolTypes(v []string) {
	o.AllowedPoolTypes = v
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetConfiguration() string {
	if o == nil || IsNil(o.Configuration) {
		var ret string
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetConfigurationOk() (*string, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given string and assigns it to the Configuration field.
func (o *GetTokenDetails200ResponseData) SetConfiguration(v string) {
	o.Configuration = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *GetTokenDetails200ResponseData) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetIsValid returns the IsValid field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetIsValid() bool {
	if o == nil || IsNil(o.IsValid) {
		var ret bool
		return ret
	}
	return *o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetIsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsValid) {
		return nil, false
	}
	return o.IsValid, true
}

// HasIsValid returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasIsValid() bool {
	if o != nil && !IsNil(o.IsValid) {
		return true
	}

	return false
}

// SetIsValid gets a reference to the given bool and assigns it to the IsValid field.
func (o *GetTokenDetails200ResponseData) SetIsValid(v bool) {
	o.IsValid = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *GetTokenDetails200ResponseData) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret string
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetLastUsedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given string and assigns it to the LastUsedAt field.
func (o *GetTokenDetails200ResponseData) SetLastUsedAt(v string) {
	o.LastUsedAt = &v
}

// GetRequestCount returns the RequestCount field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetRequestCount() int32 {
	if o == nil || IsNil(o.RequestCount) {
		var ret int32
		return ret
	}
	return *o.RequestCount
}

// GetRequestCountOk returns a tuple with the RequestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetRequestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestCount) {
		return nil, false
	}
	return o.RequestCount, true
}

// HasRequestCount returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasRequestCount() bool {
	if o != nil && !IsNil(o.RequestCount) {
		return true
	}

	return false
}

// SetRequestCount gets a reference to the given int32 and assigns it to the RequestCount field.
func (o *GetTokenDetails200ResponseData) SetRequestCount(v int32) {
	o.RequestCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetTokenDetails200ResponseData) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTokenDetails200ResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetTokenDetails200ResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetTokenDetails200ResponseData) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o GetTokenDetails200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTokenDetails200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.WidgetType) {
		toSerialize["widget_type"] = o.WidgetType
	}
	if !IsNil(o.PlayerId) {
		toSerialize["player_id"] = o.PlayerId
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.AllowedPoolTypes) {
		toSerialize["allowed_pool_types"] = o.AllowedPoolTypes
	}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.IsValid) {
		toSerialize["is_valid"] = o.IsValid
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	if !IsNil(o.RequestCount) {
		toSerialize["request_count"] = o.RequestCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableGetTokenDetails200ResponseData struct {
	value *GetTokenDetails200ResponseData
	isSet bool
}

func (v NullableGetTokenDetails200ResponseData) Get() *GetTokenDetails200ResponseData {
	return v.value
}

func (v *NullableGetTokenDetails200ResponseData) Set(val *GetTokenDetails200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTokenDetails200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTokenDetails200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTokenDetails200ResponseData(val *GetTokenDetails200ResponseData) *NullableGetTokenDetails200ResponseData {
	return &NullableGetTokenDetails200ResponseData{value: val, isSet: true}
}

func (v NullableGetTokenDetails200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTokenDetails200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


