/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListOperatorsJackpotPoolsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListOperatorsJackpotPoolsRequest{}

// ListOperatorsJackpotPoolsRequest struct for ListOperatorsJackpotPoolsRequest
type ListOperatorsJackpotPoolsRequest struct {
	// Must be 3 characters.
	Currency *string `json:"currency,omitempty"`
	// 
	Status *string `json:"status,omitempty"`
	// 
	PoolType *string `json:"pool_type,omitempty"`
}

// NewListOperatorsJackpotPoolsRequest instantiates a new ListOperatorsJackpotPoolsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListOperatorsJackpotPoolsRequest() *ListOperatorsJackpotPoolsRequest {
	this := ListOperatorsJackpotPoolsRequest{}
	return &this
}

// NewListOperatorsJackpotPoolsRequestWithDefaults instantiates a new ListOperatorsJackpotPoolsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListOperatorsJackpotPoolsRequestWithDefaults() *ListOperatorsJackpotPoolsRequest {
	this := ListOperatorsJackpotPoolsRequest{}
	return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ListOperatorsJackpotPoolsRequest) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperatorsJackpotPoolsRequest) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ListOperatorsJackpotPoolsRequest) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ListOperatorsJackpotPoolsRequest) SetCurrency(v string) {
	o.Currency = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *ListOperatorsJackpotPoolsRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperatorsJackpotPoolsRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *ListOperatorsJackpotPoolsRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *ListOperatorsJackpotPoolsRequest) SetStatus(v string) {
	o.Status = &v
}

// GetPoolType returns the PoolType field value if set, zero value otherwise.
func (o *ListOperatorsJackpotPoolsRequest) GetPoolType() string {
	if o == nil || IsNil(o.PoolType) {
		var ret string
		return ret
	}
	return *o.PoolType
}

// GetPoolTypeOk returns a tuple with the PoolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListOperatorsJackpotPoolsRequest) GetPoolTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PoolType) {
		return nil, false
	}
	return o.PoolType, true
}

// HasPoolType returns a boolean if a field has been set.
func (o *ListOperatorsJackpotPoolsRequest) HasPoolType() bool {
	if o != nil && !IsNil(o.PoolType) {
		return true
	}

	return false
}

// SetPoolType gets a reference to the given string and assigns it to the PoolType field.
func (o *ListOperatorsJackpotPoolsRequest) SetPoolType(v string) {
	o.PoolType = &v
}

func (o ListOperatorsJackpotPoolsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListOperatorsJackpotPoolsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PoolType) {
		toSerialize["pool_type"] = o.PoolType
	}
	return toSerialize, nil
}

type NullableListOperatorsJackpotPoolsRequest struct {
	value *ListOperatorsJackpotPoolsRequest
	isSet bool
}

func (v NullableListOperatorsJackpotPoolsRequest) Get() *ListOperatorsJackpotPoolsRequest {
	return v.value
}

func (v *NullableListOperatorsJackpotPoolsRequest) Set(val *ListOperatorsJackpotPoolsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListOperatorsJackpotPoolsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListOperatorsJackpotPoolsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListOperatorsJackpotPoolsRequest(val *ListOperatorsJackpotPoolsRequest) *NullableListOperatorsJackpotPoolsRequest {
	return &NullableListOperatorsJackpotPoolsRequest{value: val, isSet: true}
}

func (v NullableListOperatorsJackpotPoolsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListOperatorsJackpotPoolsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


