/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostApiV1GameTransactionsExportRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostApiV1GameTransactionsExportRequest{}

// PostApiV1GameTransactionsExportRequest struct for PostApiV1GameTransactionsExportRequest
type PostApiV1GameTransactionsExportRequest struct {
	// 
	Format string `json:"format"`
	// Must be a valid date.
	FromDate string `json:"from_date"`
	// Must be a valid date. Must be a date after or equal to <code>from_date</code>.
	ToDate string `json:"to_date"`
	// 
	PlayerId NullableString `json:"player_id,omitempty"`
	// The <code>id</code> of an existing record in the games table.
	GameId NullableInt32 `json:"game_id,omitempty"`
	// 
	Type NullableString `json:"type,omitempty"`
	// 
	IncludeSummary *bool `json:"include_summary,omitempty"`
	// 
	Async *bool `json:"async,omitempty"`
}

type _PostApiV1GameTransactionsExportRequest PostApiV1GameTransactionsExportRequest

// NewPostApiV1GameTransactionsExportRequest instantiates a new PostApiV1GameTransactionsExportRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostApiV1GameTransactionsExportRequest(format string, fromDate string, toDate string) *PostApiV1GameTransactionsExportRequest {
	this := PostApiV1GameTransactionsExportRequest{}
	this.Format = format
	this.FromDate = fromDate
	this.ToDate = toDate
	return &this
}

// NewPostApiV1GameTransactionsExportRequestWithDefaults instantiates a new PostApiV1GameTransactionsExportRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostApiV1GameTransactionsExportRequestWithDefaults() *PostApiV1GameTransactionsExportRequest {
	this := PostApiV1GameTransactionsExportRequest{}
	return &this
}

// GetFormat returns the Format field value
func (o *PostApiV1GameTransactionsExportRequest) GetFormat() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Format
}

// GetFormatOk returns a tuple with the Format field value
// and a boolean to check if the value has been set.
func (o *PostApiV1GameTransactionsExportRequest) GetFormatOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Format, true
}

// SetFormat sets field value
func (o *PostApiV1GameTransactionsExportRequest) SetFormat(v string) {
	o.Format = v
}

// GetFromDate returns the FromDate field value
func (o *PostApiV1GameTransactionsExportRequest) GetFromDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FromDate
}

// GetFromDateOk returns a tuple with the FromDate field value
// and a boolean to check if the value has been set.
func (o *PostApiV1GameTransactionsExportRequest) GetFromDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FromDate, true
}

// SetFromDate sets field value
func (o *PostApiV1GameTransactionsExportRequest) SetFromDate(v string) {
	o.FromDate = v
}

// GetToDate returns the ToDate field value
func (o *PostApiV1GameTransactionsExportRequest) GetToDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ToDate
}

// GetToDateOk returns a tuple with the ToDate field value
// and a boolean to check if the value has been set.
func (o *PostApiV1GameTransactionsExportRequest) GetToDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ToDate, true
}

// SetToDate sets field value
func (o *PostApiV1GameTransactionsExportRequest) SetToDate(v string) {
	o.ToDate = v
}

// GetPlayerId returns the PlayerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostApiV1GameTransactionsExportRequest) GetPlayerId() string {
	if o == nil || IsNil(o.PlayerId.Get()) {
		var ret string
		return ret
	}
	return *o.PlayerId.Get()
}

// GetPlayerIdOk returns a tuple with the PlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostApiV1GameTransactionsExportRequest) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlayerId.Get(), o.PlayerId.IsSet()
}

// HasPlayerId returns a boolean if a field has been set.
func (o *PostApiV1GameTransactionsExportRequest) HasPlayerId() bool {
	if o != nil && o.PlayerId.IsSet() {
		return true
	}

	return false
}

// SetPlayerId gets a reference to the given NullableString and assigns it to the PlayerId field.
func (o *PostApiV1GameTransactionsExportRequest) SetPlayerId(v string) {
	o.PlayerId.Set(&v)
}
// SetPlayerIdNil sets the value for PlayerId to be an explicit nil
func (o *PostApiV1GameTransactionsExportRequest) SetPlayerIdNil() {
	o.PlayerId.Set(nil)
}

// UnsetPlayerId ensures that no value is present for PlayerId, not even an explicit nil
func (o *PostApiV1GameTransactionsExportRequest) UnsetPlayerId() {
	o.PlayerId.Unset()
}

// GetGameId returns the GameId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostApiV1GameTransactionsExportRequest) GetGameId() int32 {
	if o == nil || IsNil(o.GameId.Get()) {
		var ret int32
		return ret
	}
	return *o.GameId.Get()
}

// GetGameIdOk returns a tuple with the GameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostApiV1GameTransactionsExportRequest) GetGameIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GameId.Get(), o.GameId.IsSet()
}

// HasGameId returns a boolean if a field has been set.
func (o *PostApiV1GameTransactionsExportRequest) HasGameId() bool {
	if o != nil && o.GameId.IsSet() {
		return true
	}

	return false
}

// SetGameId gets a reference to the given NullableInt32 and assigns it to the GameId field.
func (o *PostApiV1GameTransactionsExportRequest) SetGameId(v int32) {
	o.GameId.Set(&v)
}
// SetGameIdNil sets the value for GameId to be an explicit nil
func (o *PostApiV1GameTransactionsExportRequest) SetGameIdNil() {
	o.GameId.Set(nil)
}

// UnsetGameId ensures that no value is present for GameId, not even an explicit nil
func (o *PostApiV1GameTransactionsExportRequest) UnsetGameId() {
	o.GameId.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PostApiV1GameTransactionsExportRequest) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PostApiV1GameTransactionsExportRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *PostApiV1GameTransactionsExportRequest) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *PostApiV1GameTransactionsExportRequest) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *PostApiV1GameTransactionsExportRequest) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *PostApiV1GameTransactionsExportRequest) UnsetType() {
	o.Type.Unset()
}

// GetIncludeSummary returns the IncludeSummary field value if set, zero value otherwise.
func (o *PostApiV1GameTransactionsExportRequest) GetIncludeSummary() bool {
	if o == nil || IsNil(o.IncludeSummary) {
		var ret bool
		return ret
	}
	return *o.IncludeSummary
}

// GetIncludeSummaryOk returns a tuple with the IncludeSummary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostApiV1GameTransactionsExportRequest) GetIncludeSummaryOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeSummary) {
		return nil, false
	}
	return o.IncludeSummary, true
}

// HasIncludeSummary returns a boolean if a field has been set.
func (o *PostApiV1GameTransactionsExportRequest) HasIncludeSummary() bool {
	if o != nil && !IsNil(o.IncludeSummary) {
		return true
	}

	return false
}

// SetIncludeSummary gets a reference to the given bool and assigns it to the IncludeSummary field.
func (o *PostApiV1GameTransactionsExportRequest) SetIncludeSummary(v bool) {
	o.IncludeSummary = &v
}

// GetAsync returns the Async field value if set, zero value otherwise.
func (o *PostApiV1GameTransactionsExportRequest) GetAsync() bool {
	if o == nil || IsNil(o.Async) {
		var ret bool
		return ret
	}
	return *o.Async
}

// GetAsyncOk returns a tuple with the Async field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostApiV1GameTransactionsExportRequest) GetAsyncOk() (*bool, bool) {
	if o == nil || IsNil(o.Async) {
		return nil, false
	}
	return o.Async, true
}

// HasAsync returns a boolean if a field has been set.
func (o *PostApiV1GameTransactionsExportRequest) HasAsync() bool {
	if o != nil && !IsNil(o.Async) {
		return true
	}

	return false
}

// SetAsync gets a reference to the given bool and assigns it to the Async field.
func (o *PostApiV1GameTransactionsExportRequest) SetAsync(v bool) {
	o.Async = &v
}

func (o PostApiV1GameTransactionsExportRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostApiV1GameTransactionsExportRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["format"] = o.Format
	toSerialize["from_date"] = o.FromDate
	toSerialize["to_date"] = o.ToDate
	if o.PlayerId.IsSet() {
		toSerialize["player_id"] = o.PlayerId.Get()
	}
	if o.GameId.IsSet() {
		toSerialize["game_id"] = o.GameId.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if !IsNil(o.IncludeSummary) {
		toSerialize["include_summary"] = o.IncludeSummary
	}
	if !IsNil(o.Async) {
		toSerialize["async"] = o.Async
	}
	return toSerialize, nil
}

func (o *PostApiV1GameTransactionsExportRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"format",
		"from_date",
		"to_date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostApiV1GameTransactionsExportRequest := _PostApiV1GameTransactionsExportRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostApiV1GameTransactionsExportRequest)

	if err != nil {
		return err
	}

	*o = PostApiV1GameTransactionsExportRequest(varPostApiV1GameTransactionsExportRequest)

	return err
}

type NullablePostApiV1GameTransactionsExportRequest struct {
	value *PostApiV1GameTransactionsExportRequest
	isSet bool
}

func (v NullablePostApiV1GameTransactionsExportRequest) Get() *PostApiV1GameTransactionsExportRequest {
	return v.value
}

func (v *NullablePostApiV1GameTransactionsExportRequest) Set(val *PostApiV1GameTransactionsExportRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostApiV1GameTransactionsExportRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostApiV1GameTransactionsExportRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostApiV1GameTransactionsExportRequest(val *PostApiV1GameTransactionsExportRequest) *NullablePostApiV1GameTransactionsExportRequest {
	return &NullablePostApiV1GameTransactionsExportRequest{value: val, isSet: true}
}

func (v NullablePostApiV1GameTransactionsExportRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostApiV1GameTransactionsExportRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


