/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegisterANewDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterANewDomainRequest{}

// RegisterANewDomainRequest struct for RegisterANewDomainRequest
type RegisterANewDomainRequest struct {
	// The domain to register (e.g., \"casino.example.com\").
	Domain string `json:"domain"`
	// optional List of allowed widget types. Default: [\"jackpot\"].
	AllowedWidgets []string `json:"allowed_widgets,omitempty"`
}

type _RegisterANewDomainRequest RegisterANewDomainRequest

// NewRegisterANewDomainRequest instantiates a new RegisterANewDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterANewDomainRequest(domain string) *RegisterANewDomainRequest {
	this := RegisterANewDomainRequest{}
	this.Domain = domain
	return &this
}

// NewRegisterANewDomainRequestWithDefaults instantiates a new RegisterANewDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterANewDomainRequestWithDefaults() *RegisterANewDomainRequest {
	this := RegisterANewDomainRequest{}
	return &this
}

// GetDomain returns the Domain field value
func (o *RegisterANewDomainRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *RegisterANewDomainRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *RegisterANewDomainRequest) SetDomain(v string) {
	o.Domain = v
}

// GetAllowedWidgets returns the AllowedWidgets field value if set, zero value otherwise.
func (o *RegisterANewDomainRequest) GetAllowedWidgets() []string {
	if o == nil || IsNil(o.AllowedWidgets) {
		var ret []string
		return ret
	}
	return o.AllowedWidgets
}

// GetAllowedWidgetsOk returns a tuple with the AllowedWidgets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomainRequest) GetAllowedWidgetsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedWidgets) {
		return nil, false
	}
	return o.AllowedWidgets, true
}

// HasAllowedWidgets returns a boolean if a field has been set.
func (o *RegisterANewDomainRequest) HasAllowedWidgets() bool {
	if o != nil && !IsNil(o.AllowedWidgets) {
		return true
	}

	return false
}

// SetAllowedWidgets gets a reference to the given []string and assigns it to the AllowedWidgets field.
func (o *RegisterANewDomainRequest) SetAllowedWidgets(v []string) {
	o.AllowedWidgets = v
}

func (o RegisterANewDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterANewDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	if !IsNil(o.AllowedWidgets) {
		toSerialize["allowed_widgets"] = o.AllowedWidgets
	}
	return toSerialize, nil
}

func (o *RegisterANewDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegisterANewDomainRequest := _RegisterANewDomainRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegisterANewDomainRequest)

	if err != nil {
		return err
	}

	*o = RegisterANewDomainRequest(varRegisterANewDomainRequest)

	return err
}

type NullableRegisterANewDomainRequest struct {
	value *RegisterANewDomainRequest
	isSet bool
}

func (v NullableRegisterANewDomainRequest) Get() *RegisterANewDomainRequest {
	return v.value
}

func (v *NullableRegisterANewDomainRequest) Set(val *RegisterANewDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterANewDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterANewDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterANewDomainRequest(val *RegisterANewDomainRequest) *NullableRegisterANewDomainRequest {
	return &NullableRegisterANewDomainRequest{value: val, isSet: true}
}

func (v NullableRegisterANewDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterANewDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


