/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the CancelAStandaloneFreespinRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelAStandaloneFreespinRequest{}

// CancelAStandaloneFreespinRequest struct for CancelAStandaloneFreespinRequest
type CancelAStandaloneFreespinRequest struct {
	// optional Reason for cancellation.
	Reason NullableString `json:"reason,omitempty"`
}

// NewCancelAStandaloneFreespinRequest instantiates a new CancelAStandaloneFreespinRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelAStandaloneFreespinRequest() *CancelAStandaloneFreespinRequest {
	this := CancelAStandaloneFreespinRequest{}
	return &this
}

// NewCancelAStandaloneFreespinRequestWithDefaults instantiates a new CancelAStandaloneFreespinRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelAStandaloneFreespinRequestWithDefaults() *CancelAStandaloneFreespinRequest {
	this := CancelAStandaloneFreespinRequest{}
	return &this
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CancelAStandaloneFreespinRequest) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CancelAStandaloneFreespinRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespinRequest) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *CancelAStandaloneFreespinRequest) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *CancelAStandaloneFreespinRequest) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *CancelAStandaloneFreespinRequest) UnsetReason() {
	o.Reason.Unset()
}

func (o CancelAStandaloneFreespinRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelAStandaloneFreespinRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	return toSerialize, nil
}

type NullableCancelAStandaloneFreespinRequest struct {
	value *CancelAStandaloneFreespinRequest
	isSet bool
}

func (v NullableCancelAStandaloneFreespinRequest) Get() *CancelAStandaloneFreespinRequest {
	return v.value
}

func (v *NullableCancelAStandaloneFreespinRequest) Set(val *CancelAStandaloneFreespinRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelAStandaloneFreespinRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelAStandaloneFreespinRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelAStandaloneFreespinRequest(val *CancelAStandaloneFreespinRequest) *NullableCancelAStandaloneFreespinRequest {
	return &NullableCancelAStandaloneFreespinRequest{value: val, isSet: true}
}

func (v NullableCancelAStandaloneFreespinRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelAStandaloneFreespinRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


