/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetGamesForAPoolTypeOrAllPoolTypesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGamesForAPoolTypeOrAllPoolTypesRequest{}

// GetGamesForAPoolTypeOrAllPoolTypesRequest struct for GetGamesForAPoolTypeOrAllPoolTypesRequest
type GetGamesForAPoolTypeOrAllPoolTypesRequest struct {
	// 
	PoolType *string `json:"pool_type,omitempty"`
}

// NewGetGamesForAPoolTypeOrAllPoolTypesRequest instantiates a new GetGamesForAPoolTypeOrAllPoolTypesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGamesForAPoolTypeOrAllPoolTypesRequest() *GetGamesForAPoolTypeOrAllPoolTypesRequest {
	this := GetGamesForAPoolTypeOrAllPoolTypesRequest{}
	return &this
}

// NewGetGamesForAPoolTypeOrAllPoolTypesRequestWithDefaults instantiates a new GetGamesForAPoolTypeOrAllPoolTypesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGamesForAPoolTypeOrAllPoolTypesRequestWithDefaults() *GetGamesForAPoolTypeOrAllPoolTypesRequest {
	this := GetGamesForAPoolTypeOrAllPoolTypesRequest{}
	return &this
}

// GetPoolType returns the PoolType field value if set, zero value otherwise.
func (o *GetGamesForAPoolTypeOrAllPoolTypesRequest) GetPoolType() string {
	if o == nil || IsNil(o.PoolType) {
		var ret string
		return ret
	}
	return *o.PoolType
}

// GetPoolTypeOk returns a tuple with the PoolType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGamesForAPoolTypeOrAllPoolTypesRequest) GetPoolTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PoolType) {
		return nil, false
	}
	return o.PoolType, true
}

// HasPoolType returns a boolean if a field has been set.
func (o *GetGamesForAPoolTypeOrAllPoolTypesRequest) HasPoolType() bool {
	if o != nil && !IsNil(o.PoolType) {
		return true
	}

	return false
}

// SetPoolType gets a reference to the given string and assigns it to the PoolType field.
func (o *GetGamesForAPoolTypeOrAllPoolTypesRequest) SetPoolType(v string) {
	o.PoolType = &v
}

func (o GetGamesForAPoolTypeOrAllPoolTypesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGamesForAPoolTypeOrAllPoolTypesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PoolType) {
		toSerialize["pool_type"] = o.PoolType
	}
	return toSerialize, nil
}

type NullableGetGamesForAPoolTypeOrAllPoolTypesRequest struct {
	value *GetGamesForAPoolTypeOrAllPoolTypesRequest
	isSet bool
}

func (v NullableGetGamesForAPoolTypeOrAllPoolTypesRequest) Get() *GetGamesForAPoolTypeOrAllPoolTypesRequest {
	return v.value
}

func (v *NullableGetGamesForAPoolTypeOrAllPoolTypesRequest) Set(val *GetGamesForAPoolTypeOrAllPoolTypesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGamesForAPoolTypeOrAllPoolTypesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGamesForAPoolTypeOrAllPoolTypesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGamesForAPoolTypeOrAllPoolTypesRequest(val *GetGamesForAPoolTypeOrAllPoolTypesRequest) *NullableGetGamesForAPoolTypeOrAllPoolTypesRequest {
	return &NullableGetGamesForAPoolTypeOrAllPoolTypesRequest{value: val, isSet: true}
}

func (v NullableGetGamesForAPoolTypeOrAllPoolTypesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGamesForAPoolTypeOrAllPoolTypesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


