/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateAStandaloneFreespinRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAStandaloneFreespinRequest{}

// CreateAStandaloneFreespinRequest struct for CreateAStandaloneFreespinRequest
type CreateAStandaloneFreespinRequest struct {
	// The internal game ID.
	GameId int32 `json:"game_id"`
	// The player's ID in your system.
	PlayerId string `json:"player_id"`
	// Three-letter currency code (ISO 4217).
	Currency string `json:"currency"`
	// Your unique identifier for this freespin campaign.
	FreespinId string `json:"freespin_id"`
	// Number of free spins to award (1-1000).
	FreespinCount int32 `json:"freespin_count"`
	// optional Bet amount per free spin (0.01-1000).
	FreespinBetAmount NullableNumeric `json:"freespin_bet_amount,omitempty"`
	// optional Expiration in days, default 7, max 30.
	ExpireDays NullableInt32 `json:"expire_days,omitempty"`
	// optional Specific provider slug to use.
	Provider NullableString `json:"provider,omitempty"`
}

type _CreateAStandaloneFreespinRequest CreateAStandaloneFreespinRequest

// NewCreateAStandaloneFreespinRequest instantiates a new CreateAStandaloneFreespinRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAStandaloneFreespinRequest(gameId int32, playerId string, currency string, freespinId string, freespinCount int32) *CreateAStandaloneFreespinRequest {
	this := CreateAStandaloneFreespinRequest{}
	this.GameId = gameId
	this.PlayerId = playerId
	this.Currency = currency
	this.FreespinId = freespinId
	this.FreespinCount = freespinCount
	return &this
}

// NewCreateAStandaloneFreespinRequestWithDefaults instantiates a new CreateAStandaloneFreespinRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAStandaloneFreespinRequestWithDefaults() *CreateAStandaloneFreespinRequest {
	this := CreateAStandaloneFreespinRequest{}
	return &this
}

// GetGameId returns the GameId field value
func (o *CreateAStandaloneFreespinRequest) GetGameId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GameId
}

// GetGameIdOk returns a tuple with the GameId field value
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespinRequest) GetGameIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GameId, true
}

// SetGameId sets field value
func (o *CreateAStandaloneFreespinRequest) SetGameId(v int32) {
	o.GameId = v
}

// GetPlayerId returns the PlayerId field value
func (o *CreateAStandaloneFreespinRequest) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespinRequest) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *CreateAStandaloneFreespinRequest) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetCurrency returns the Currency field value
func (o *CreateAStandaloneFreespinRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespinRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CreateAStandaloneFreespinRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetFreespinId returns the FreespinId field value
func (o *CreateAStandaloneFreespinRequest) GetFreespinId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FreespinId
}

// GetFreespinIdOk returns a tuple with the FreespinId field value
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespinRequest) GetFreespinIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreespinId, true
}

// SetFreespinId sets field value
func (o *CreateAStandaloneFreespinRequest) SetFreespinId(v string) {
	o.FreespinId = v
}

// GetFreespinCount returns the FreespinCount field value
func (o *CreateAStandaloneFreespinRequest) GetFreespinCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.FreespinCount
}

// GetFreespinCountOk returns a tuple with the FreespinCount field value
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespinRequest) GetFreespinCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FreespinCount, true
}

// SetFreespinCount sets field value
func (o *CreateAStandaloneFreespinRequest) SetFreespinCount(v int32) {
	o.FreespinCount = v
}

// GetFreespinBetAmount returns the FreespinBetAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAStandaloneFreespinRequest) GetFreespinBetAmount() Numeric {
	if o == nil || IsNil(o.FreespinBetAmount.Get()) {
		var ret Numeric
		return ret
	}
	return *o.FreespinBetAmount.Get()
}

// GetFreespinBetAmountOk returns a tuple with the FreespinBetAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAStandaloneFreespinRequest) GetFreespinBetAmountOk() (*Numeric, bool) {
	if o == nil {
		return nil, false
	}
	return o.FreespinBetAmount.Get(), o.FreespinBetAmount.IsSet()
}

// HasFreespinBetAmount returns a boolean if a field has been set.
func (o *CreateAStandaloneFreespinRequest) HasFreespinBetAmount() bool {
	if o != nil && o.FreespinBetAmount.IsSet() {
		return true
	}

	return false
}

// SetFreespinBetAmount gets a reference to the given NullableNumeric and assigns it to the FreespinBetAmount field.
func (o *CreateAStandaloneFreespinRequest) SetFreespinBetAmount(v Numeric) {
	o.FreespinBetAmount.Set(&v)
}
// SetFreespinBetAmountNil sets the value for FreespinBetAmount to be an explicit nil
func (o *CreateAStandaloneFreespinRequest) SetFreespinBetAmountNil() {
	o.FreespinBetAmount.Set(nil)
}

// UnsetFreespinBetAmount ensures that no value is present for FreespinBetAmount, not even an explicit nil
func (o *CreateAStandaloneFreespinRequest) UnsetFreespinBetAmount() {
	o.FreespinBetAmount.Unset()
}

// GetExpireDays returns the ExpireDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAStandaloneFreespinRequest) GetExpireDays() int32 {
	if o == nil || IsNil(o.ExpireDays.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpireDays.Get()
}

// GetExpireDaysOk returns a tuple with the ExpireDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAStandaloneFreespinRequest) GetExpireDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpireDays.Get(), o.ExpireDays.IsSet()
}

// HasExpireDays returns a boolean if a field has been set.
func (o *CreateAStandaloneFreespinRequest) HasExpireDays() bool {
	if o != nil && o.ExpireDays.IsSet() {
		return true
	}

	return false
}

// SetExpireDays gets a reference to the given NullableInt32 and assigns it to the ExpireDays field.
func (o *CreateAStandaloneFreespinRequest) SetExpireDays(v int32) {
	o.ExpireDays.Set(&v)
}
// SetExpireDaysNil sets the value for ExpireDays to be an explicit nil
func (o *CreateAStandaloneFreespinRequest) SetExpireDaysNil() {
	o.ExpireDays.Set(nil)
}

// UnsetExpireDays ensures that no value is present for ExpireDays, not even an explicit nil
func (o *CreateAStandaloneFreespinRequest) UnsetExpireDays() {
	o.ExpireDays.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAStandaloneFreespinRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAStandaloneFreespinRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *CreateAStandaloneFreespinRequest) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *CreateAStandaloneFreespinRequest) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *CreateAStandaloneFreespinRequest) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *CreateAStandaloneFreespinRequest) UnsetProvider() {
	o.Provider.Unset()
}

func (o CreateAStandaloneFreespinRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAStandaloneFreespinRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["game_id"] = o.GameId
	toSerialize["player_id"] = o.PlayerId
	toSerialize["currency"] = o.Currency
	toSerialize["freespin_id"] = o.FreespinId
	toSerialize["freespin_count"] = o.FreespinCount
	if o.FreespinBetAmount.IsSet() {
		toSerialize["freespin_bet_amount"] = o.FreespinBetAmount.Get()
	}
	if o.ExpireDays.IsSet() {
		toSerialize["expire_days"] = o.ExpireDays.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	return toSerialize, nil
}

func (o *CreateAStandaloneFreespinRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"game_id",
		"player_id",
		"currency",
		"freespin_id",
		"freespin_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAStandaloneFreespinRequest := _CreateAStandaloneFreespinRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateAStandaloneFreespinRequest)

	if err != nil {
		return err
	}

	*o = CreateAStandaloneFreespinRequest(varCreateAStandaloneFreespinRequest)

	return err
}

type NullableCreateAStandaloneFreespinRequest struct {
	value *CreateAStandaloneFreespinRequest
	isSet bool
}

func (v NullableCreateAStandaloneFreespinRequest) Get() *CreateAStandaloneFreespinRequest {
	return v.value
}

func (v *NullableCreateAStandaloneFreespinRequest) Set(val *CreateAStandaloneFreespinRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAStandaloneFreespinRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAStandaloneFreespinRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAStandaloneFreespinRequest(val *CreateAStandaloneFreespinRequest) *NullableCreateAStandaloneFreespinRequest {
	return &NullableCreateAStandaloneFreespinRequest{value: val, isSet: true}
}

func (v NullableCreateAStandaloneFreespinRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAStandaloneFreespinRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


