/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the StartAMultiSession201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartAMultiSession201ResponseData{}

// StartAMultiSession201ResponseData struct for StartAMultiSession201ResponseData
type StartAMultiSession201ResponseData struct {
	MultiSessionId *string `json:"multi_session_id,omitempty"`
	SwipeUrl *string `json:"swipe_url,omitempty"`
	TotalGames *int32 `json:"total_games,omitempty"`
	Games []StartAMultiSession201ResponseDataGamesInner `json:"games,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// NewStartAMultiSession201ResponseData instantiates a new StartAMultiSession201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartAMultiSession201ResponseData() *StartAMultiSession201ResponseData {
	this := StartAMultiSession201ResponseData{}
	return &this
}

// NewStartAMultiSession201ResponseDataWithDefaults instantiates a new StartAMultiSession201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartAMultiSession201ResponseDataWithDefaults() *StartAMultiSession201ResponseData {
	this := StartAMultiSession201ResponseData{}
	return &this
}

// GetMultiSessionId returns the MultiSessionId field value if set, zero value otherwise.
func (o *StartAMultiSession201ResponseData) GetMultiSessionId() string {
	if o == nil || IsNil(o.MultiSessionId) {
		var ret string
		return ret
	}
	return *o.MultiSessionId
}

// GetMultiSessionIdOk returns a tuple with the MultiSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAMultiSession201ResponseData) GetMultiSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.MultiSessionId) {
		return nil, false
	}
	return o.MultiSessionId, true
}

// HasMultiSessionId returns a boolean if a field has been set.
func (o *StartAMultiSession201ResponseData) HasMultiSessionId() bool {
	if o != nil && !IsNil(o.MultiSessionId) {
		return true
	}

	return false
}

// SetMultiSessionId gets a reference to the given string and assigns it to the MultiSessionId field.
func (o *StartAMultiSession201ResponseData) SetMultiSessionId(v string) {
	o.MultiSessionId = &v
}

// GetSwipeUrl returns the SwipeUrl field value if set, zero value otherwise.
func (o *StartAMultiSession201ResponseData) GetSwipeUrl() string {
	if o == nil || IsNil(o.SwipeUrl) {
		var ret string
		return ret
	}
	return *o.SwipeUrl
}

// GetSwipeUrlOk returns a tuple with the SwipeUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAMultiSession201ResponseData) GetSwipeUrlOk() (*string, bool) {
	if o == nil || IsNil(o.SwipeUrl) {
		return nil, false
	}
	return o.SwipeUrl, true
}

// HasSwipeUrl returns a boolean if a field has been set.
func (o *StartAMultiSession201ResponseData) HasSwipeUrl() bool {
	if o != nil && !IsNil(o.SwipeUrl) {
		return true
	}

	return false
}

// SetSwipeUrl gets a reference to the given string and assigns it to the SwipeUrl field.
func (o *StartAMultiSession201ResponseData) SetSwipeUrl(v string) {
	o.SwipeUrl = &v
}

// GetTotalGames returns the TotalGames field value if set, zero value otherwise.
func (o *StartAMultiSession201ResponseData) GetTotalGames() int32 {
	if o == nil || IsNil(o.TotalGames) {
		var ret int32
		return ret
	}
	return *o.TotalGames
}

// GetTotalGamesOk returns a tuple with the TotalGames field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAMultiSession201ResponseData) GetTotalGamesOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalGames) {
		return nil, false
	}
	return o.TotalGames, true
}

// HasTotalGames returns a boolean if a field has been set.
func (o *StartAMultiSession201ResponseData) HasTotalGames() bool {
	if o != nil && !IsNil(o.TotalGames) {
		return true
	}

	return false
}

// SetTotalGames gets a reference to the given int32 and assigns it to the TotalGames field.
func (o *StartAMultiSession201ResponseData) SetTotalGames(v int32) {
	o.TotalGames = &v
}

// GetGames returns the Games field value if set, zero value otherwise.
func (o *StartAMultiSession201ResponseData) GetGames() []StartAMultiSession201ResponseDataGamesInner {
	if o == nil || IsNil(o.Games) {
		var ret []StartAMultiSession201ResponseDataGamesInner
		return ret
	}
	return o.Games
}

// GetGamesOk returns a tuple with the Games field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAMultiSession201ResponseData) GetGamesOk() ([]StartAMultiSession201ResponseDataGamesInner, bool) {
	if o == nil || IsNil(o.Games) {
		return nil, false
	}
	return o.Games, true
}

// HasGames returns a boolean if a field has been set.
func (o *StartAMultiSession201ResponseData) HasGames() bool {
	if o != nil && !IsNil(o.Games) {
		return true
	}

	return false
}

// SetGames gets a reference to the given []StartAMultiSession201ResponseDataGamesInner and assigns it to the Games field.
func (o *StartAMultiSession201ResponseData) SetGames(v []StartAMultiSession201ResponseDataGamesInner) {
	o.Games = v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *StartAMultiSession201ResponseData) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAMultiSession201ResponseData) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *StartAMultiSession201ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *StartAMultiSession201ResponseData) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

func (o StartAMultiSession201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartAMultiSession201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MultiSessionId) {
		toSerialize["multi_session_id"] = o.MultiSessionId
	}
	if !IsNil(o.SwipeUrl) {
		toSerialize["swipe_url"] = o.SwipeUrl
	}
	if !IsNil(o.TotalGames) {
		toSerialize["total_games"] = o.TotalGames
	}
	if !IsNil(o.Games) {
		toSerialize["games"] = o.Games
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableStartAMultiSession201ResponseData struct {
	value *StartAMultiSession201ResponseData
	isSet bool
}

func (v NullableStartAMultiSession201ResponseData) Get() *StartAMultiSession201ResponseData {
	return v.value
}

func (v *NullableStartAMultiSession201ResponseData) Set(val *StartAMultiSession201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableStartAMultiSession201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableStartAMultiSession201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartAMultiSession201ResponseData(val *StartAMultiSession201ResponseData) *NullableStartAMultiSession201ResponseData {
	return &NullableStartAMultiSession201ResponseData{value: val, isSet: true}
}

func (v NullableStartAMultiSession201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartAMultiSession201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


