/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ConfigureJackpotSettingsForTheOperatorRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureJackpotSettingsForTheOperatorRequest{}

// ConfigureJackpotSettingsForTheOperatorRequest struct for ConfigureJackpotSettingsForTheOperatorRequest
type ConfigureJackpotSettingsForTheOperatorRequest struct {
	// 
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// 
	PoolTypes []string `json:"pool_types,omitempty"`
	// Must be at least 0. Must not be greater than 0.9.
	CasinoCutPercentage *float32 `json:"casino_cut_percentage,omitempty"`
	// Must be at least 1. Must not be greater than 10000.
	WinnerCount *int32 `json:"winner_count,omitempty"`
	// 
	DistributionMethod *string `json:"distribution_method,omitempty"`
	// 
	WeightCalculation *string `json:"weight_calculation,omitempty"`
	// 
	PrizeTiers []ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner `json:"prize_tiers,omitempty"`
	// 
	GameFilterEnabled *bool `json:"game_filter_enabled,omitempty"`
	// 
	WebhookEnabled *bool `json:"webhook_enabled,omitempty"`
	// Must be at least 1. Must not be greater than 168.
	ReminderHoursBefore NullableInt32 `json:"reminder_hours_before,omitempty"`
}

// NewConfigureJackpotSettingsForTheOperatorRequest instantiates a new ConfigureJackpotSettingsForTheOperatorRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureJackpotSettingsForTheOperatorRequest() *ConfigureJackpotSettingsForTheOperatorRequest {
	this := ConfigureJackpotSettingsForTheOperatorRequest{}
	return &this
}

// NewConfigureJackpotSettingsForTheOperatorRequestWithDefaults instantiates a new ConfigureJackpotSettingsForTheOperatorRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureJackpotSettingsForTheOperatorRequestWithDefaults() *ConfigureJackpotSettingsForTheOperatorRequest {
	this := ConfigureJackpotSettingsForTheOperatorRequest{}
	return &this
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetPoolTypes returns the PoolTypes field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetPoolTypes() []string {
	if o == nil || IsNil(o.PoolTypes) {
		var ret []string
		return ret
	}
	return o.PoolTypes
}

// GetPoolTypesOk returns a tuple with the PoolTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetPoolTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.PoolTypes) {
		return nil, false
	}
	return o.PoolTypes, true
}

// HasPoolTypes returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasPoolTypes() bool {
	if o != nil && !IsNil(o.PoolTypes) {
		return true
	}

	return false
}

// SetPoolTypes gets a reference to the given []string and assigns it to the PoolTypes field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetPoolTypes(v []string) {
	o.PoolTypes = v
}

// GetCasinoCutPercentage returns the CasinoCutPercentage field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetCasinoCutPercentage() float32 {
	if o == nil || IsNil(o.CasinoCutPercentage) {
		var ret float32
		return ret
	}
	return *o.CasinoCutPercentage
}

// GetCasinoCutPercentageOk returns a tuple with the CasinoCutPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetCasinoCutPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.CasinoCutPercentage) {
		return nil, false
	}
	return o.CasinoCutPercentage, true
}

// HasCasinoCutPercentage returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasCasinoCutPercentage() bool {
	if o != nil && !IsNil(o.CasinoCutPercentage) {
		return true
	}

	return false
}

// SetCasinoCutPercentage gets a reference to the given float32 and assigns it to the CasinoCutPercentage field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetCasinoCutPercentage(v float32) {
	o.CasinoCutPercentage = &v
}

// GetWinnerCount returns the WinnerCount field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetWinnerCount() int32 {
	if o == nil || IsNil(o.WinnerCount) {
		var ret int32
		return ret
	}
	return *o.WinnerCount
}

// GetWinnerCountOk returns a tuple with the WinnerCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetWinnerCountOk() (*int32, bool) {
	if o == nil || IsNil(o.WinnerCount) {
		return nil, false
	}
	return o.WinnerCount, true
}

// HasWinnerCount returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasWinnerCount() bool {
	if o != nil && !IsNil(o.WinnerCount) {
		return true
	}

	return false
}

// SetWinnerCount gets a reference to the given int32 and assigns it to the WinnerCount field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetWinnerCount(v int32) {
	o.WinnerCount = &v
}

// GetDistributionMethod returns the DistributionMethod field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetDistributionMethod() string {
	if o == nil || IsNil(o.DistributionMethod) {
		var ret string
		return ret
	}
	return *o.DistributionMethod
}

// GetDistributionMethodOk returns a tuple with the DistributionMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetDistributionMethodOk() (*string, bool) {
	if o == nil || IsNil(o.DistributionMethod) {
		return nil, false
	}
	return o.DistributionMethod, true
}

// HasDistributionMethod returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasDistributionMethod() bool {
	if o != nil && !IsNil(o.DistributionMethod) {
		return true
	}

	return false
}

// SetDistributionMethod gets a reference to the given string and assigns it to the DistributionMethod field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetDistributionMethod(v string) {
	o.DistributionMethod = &v
}

// GetWeightCalculation returns the WeightCalculation field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetWeightCalculation() string {
	if o == nil || IsNil(o.WeightCalculation) {
		var ret string
		return ret
	}
	return *o.WeightCalculation
}

// GetWeightCalculationOk returns a tuple with the WeightCalculation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetWeightCalculationOk() (*string, bool) {
	if o == nil || IsNil(o.WeightCalculation) {
		return nil, false
	}
	return o.WeightCalculation, true
}

// HasWeightCalculation returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasWeightCalculation() bool {
	if o != nil && !IsNil(o.WeightCalculation) {
		return true
	}

	return false
}

// SetWeightCalculation gets a reference to the given string and assigns it to the WeightCalculation field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetWeightCalculation(v string) {
	o.WeightCalculation = &v
}

// GetPrizeTiers returns the PrizeTiers field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetPrizeTiers() []ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner {
	if o == nil || IsNil(o.PrizeTiers) {
		var ret []ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner
		return ret
	}
	return o.PrizeTiers
}

// GetPrizeTiersOk returns a tuple with the PrizeTiers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetPrizeTiersOk() ([]ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner, bool) {
	if o == nil || IsNil(o.PrizeTiers) {
		return nil, false
	}
	return o.PrizeTiers, true
}

// HasPrizeTiers returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasPrizeTiers() bool {
	if o != nil && !IsNil(o.PrizeTiers) {
		return true
	}

	return false
}

// SetPrizeTiers gets a reference to the given []ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner and assigns it to the PrizeTiers field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetPrizeTiers(v []ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) {
	o.PrizeTiers = v
}

// GetGameFilterEnabled returns the GameFilterEnabled field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetGameFilterEnabled() bool {
	if o == nil || IsNil(o.GameFilterEnabled) {
		var ret bool
		return ret
	}
	return *o.GameFilterEnabled
}

// GetGameFilterEnabledOk returns a tuple with the GameFilterEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetGameFilterEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.GameFilterEnabled) {
		return nil, false
	}
	return o.GameFilterEnabled, true
}

// HasGameFilterEnabled returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasGameFilterEnabled() bool {
	if o != nil && !IsNil(o.GameFilterEnabled) {
		return true
	}

	return false
}

// SetGameFilterEnabled gets a reference to the given bool and assigns it to the GameFilterEnabled field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetGameFilterEnabled(v bool) {
	o.GameFilterEnabled = &v
}

// GetWebhookEnabled returns the WebhookEnabled field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetWebhookEnabled() bool {
	if o == nil || IsNil(o.WebhookEnabled) {
		var ret bool
		return ret
	}
	return *o.WebhookEnabled
}

// GetWebhookEnabledOk returns a tuple with the WebhookEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetWebhookEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.WebhookEnabled) {
		return nil, false
	}
	return o.WebhookEnabled, true
}

// HasWebhookEnabled returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasWebhookEnabled() bool {
	if o != nil && !IsNil(o.WebhookEnabled) {
		return true
	}

	return false
}

// SetWebhookEnabled gets a reference to the given bool and assigns it to the WebhookEnabled field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetWebhookEnabled(v bool) {
	o.WebhookEnabled = &v
}

// GetReminderHoursBefore returns the ReminderHoursBefore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetReminderHoursBefore() int32 {
	if o == nil || IsNil(o.ReminderHoursBefore.Get()) {
		var ret int32
		return ret
	}
	return *o.ReminderHoursBefore.Get()
}

// GetReminderHoursBeforeOk returns a tuple with the ReminderHoursBefore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConfigureJackpotSettingsForTheOperatorRequest) GetReminderHoursBeforeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReminderHoursBefore.Get(), o.ReminderHoursBefore.IsSet()
}

// HasReminderHoursBefore returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) HasReminderHoursBefore() bool {
	if o != nil && o.ReminderHoursBefore.IsSet() {
		return true
	}

	return false
}

// SetReminderHoursBefore gets a reference to the given NullableInt32 and assigns it to the ReminderHoursBefore field.
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetReminderHoursBefore(v int32) {
	o.ReminderHoursBefore.Set(&v)
}
// SetReminderHoursBeforeNil sets the value for ReminderHoursBefore to be an explicit nil
func (o *ConfigureJackpotSettingsForTheOperatorRequest) SetReminderHoursBeforeNil() {
	o.ReminderHoursBefore.Set(nil)
}

// UnsetReminderHoursBefore ensures that no value is present for ReminderHoursBefore, not even an explicit nil
func (o *ConfigureJackpotSettingsForTheOperatorRequest) UnsetReminderHoursBefore() {
	o.ReminderHoursBefore.Unset()
}

func (o ConfigureJackpotSettingsForTheOperatorRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureJackpotSettingsForTheOperatorRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	if !IsNil(o.PoolTypes) {
		toSerialize["pool_types"] = o.PoolTypes
	}
	if !IsNil(o.CasinoCutPercentage) {
		toSerialize["casino_cut_percentage"] = o.CasinoCutPercentage
	}
	if !IsNil(o.WinnerCount) {
		toSerialize["winner_count"] = o.WinnerCount
	}
	if !IsNil(o.DistributionMethod) {
		toSerialize["distribution_method"] = o.DistributionMethod
	}
	if !IsNil(o.WeightCalculation) {
		toSerialize["weight_calculation"] = o.WeightCalculation
	}
	if !IsNil(o.PrizeTiers) {
		toSerialize["prize_tiers"] = o.PrizeTiers
	}
	if !IsNil(o.GameFilterEnabled) {
		toSerialize["game_filter_enabled"] = o.GameFilterEnabled
	}
	if !IsNil(o.WebhookEnabled) {
		toSerialize["webhook_enabled"] = o.WebhookEnabled
	}
	if o.ReminderHoursBefore.IsSet() {
		toSerialize["reminder_hours_before"] = o.ReminderHoursBefore.Get()
	}
	return toSerialize, nil
}

type NullableConfigureJackpotSettingsForTheOperatorRequest struct {
	value *ConfigureJackpotSettingsForTheOperatorRequest
	isSet bool
}

func (v NullableConfigureJackpotSettingsForTheOperatorRequest) Get() *ConfigureJackpotSettingsForTheOperatorRequest {
	return v.value
}

func (v *NullableConfigureJackpotSettingsForTheOperatorRequest) Set(val *ConfigureJackpotSettingsForTheOperatorRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureJackpotSettingsForTheOperatorRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureJackpotSettingsForTheOperatorRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureJackpotSettingsForTheOperatorRequest(val *ConfigureJackpotSettingsForTheOperatorRequest) *NullableConfigureJackpotSettingsForTheOperatorRequest {
	return &NullableConfigureJackpotSettingsForTheOperatorRequest{value: val, isSet: true}
}

func (v NullableConfigureJackpotSettingsForTheOperatorRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureJackpotSettingsForTheOperatorRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


