/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the StartAGameSession201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartAGameSession201ResponseData{}

// StartAGameSession201ResponseData struct for StartAGameSession201ResponseData
type StartAGameSession201ResponseData struct {
	SessionId *string `json:"session_id,omitempty"`
	SessionToken *string `json:"session_token,omitempty"`
	GameUrl *string `json:"game_url,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
}

// NewStartAGameSession201ResponseData instantiates a new StartAGameSession201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartAGameSession201ResponseData() *StartAGameSession201ResponseData {
	this := StartAGameSession201ResponseData{}
	return &this
}

// NewStartAGameSession201ResponseDataWithDefaults instantiates a new StartAGameSession201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartAGameSession201ResponseDataWithDefaults() *StartAGameSession201ResponseData {
	this := StartAGameSession201ResponseData{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *StartAGameSession201ResponseData) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAGameSession201ResponseData) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *StartAGameSession201ResponseData) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *StartAGameSession201ResponseData) SetSessionId(v string) {
	o.SessionId = &v
}

// GetSessionToken returns the SessionToken field value if set, zero value otherwise.
func (o *StartAGameSession201ResponseData) GetSessionToken() string {
	if o == nil || IsNil(o.SessionToken) {
		var ret string
		return ret
	}
	return *o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAGameSession201ResponseData) GetSessionTokenOk() (*string, bool) {
	if o == nil || IsNil(o.SessionToken) {
		return nil, false
	}
	return o.SessionToken, true
}

// HasSessionToken returns a boolean if a field has been set.
func (o *StartAGameSession201ResponseData) HasSessionToken() bool {
	if o != nil && !IsNil(o.SessionToken) {
		return true
	}

	return false
}

// SetSessionToken gets a reference to the given string and assigns it to the SessionToken field.
func (o *StartAGameSession201ResponseData) SetSessionToken(v string) {
	o.SessionToken = &v
}

// GetGameUrl returns the GameUrl field value if set, zero value otherwise.
func (o *StartAGameSession201ResponseData) GetGameUrl() string {
	if o == nil || IsNil(o.GameUrl) {
		var ret string
		return ret
	}
	return *o.GameUrl
}

// GetGameUrlOk returns a tuple with the GameUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAGameSession201ResponseData) GetGameUrlOk() (*string, bool) {
	if o == nil || IsNil(o.GameUrl) {
		return nil, false
	}
	return o.GameUrl, true
}

// HasGameUrl returns a boolean if a field has been set.
func (o *StartAGameSession201ResponseData) HasGameUrl() bool {
	if o != nil && !IsNil(o.GameUrl) {
		return true
	}

	return false
}

// SetGameUrl gets a reference to the given string and assigns it to the GameUrl field.
func (o *StartAGameSession201ResponseData) SetGameUrl(v string) {
	o.GameUrl = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *StartAGameSession201ResponseData) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAGameSession201ResponseData) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *StartAGameSession201ResponseData) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *StartAGameSession201ResponseData) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

func (o StartAGameSession201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartAGameSession201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionId) {
		toSerialize["session_id"] = o.SessionId
	}
	if !IsNil(o.SessionToken) {
		toSerialize["session_token"] = o.SessionToken
	}
	if !IsNil(o.GameUrl) {
		toSerialize["game_url"] = o.GameUrl
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	return toSerialize, nil
}

type NullableStartAGameSession201ResponseData struct {
	value *StartAGameSession201ResponseData
	isSet bool
}

func (v NullableStartAGameSession201ResponseData) Get() *StartAGameSession201ResponseData {
	return v.value
}

func (v *NullableStartAGameSession201ResponseData) Set(val *StartAGameSession201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableStartAGameSession201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableStartAGameSession201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartAGameSession201ResponseData(val *StartAGameSession201ResponseData) *NullableStartAGameSession201ResponseData {
	return &NullableStartAGameSession201ResponseData{value: val, isSet: true}
}

func (v NullableStartAGameSession201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartAGameSession201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


