/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListGames200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGames200Response{}

// ListGames200Response struct for ListGames200Response
type ListGames200Response struct {
	Data []ListGames200ResponseDataInner `json:"data,omitempty"`
	Meta *ListGames200ResponseMeta `json:"meta,omitempty"`
}

// NewListGames200Response instantiates a new ListGames200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGames200Response() *ListGames200Response {
	this := ListGames200Response{}
	return &this
}

// NewListGames200ResponseWithDefaults instantiates a new ListGames200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGames200ResponseWithDefaults() *ListGames200Response {
	this := ListGames200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListGames200Response) GetData() []ListGames200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []ListGames200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200Response) GetDataOk() ([]ListGames200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListGames200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []ListGames200ResponseDataInner and assigns it to the Data field.
func (o *ListGames200Response) SetData(v []ListGames200ResponseDataInner) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListGames200Response) GetMeta() ListGames200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret ListGames200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200Response) GetMetaOk() (*ListGames200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListGames200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ListGames200ResponseMeta and assigns it to the Meta field.
func (o *ListGames200Response) SetMeta(v ListGames200ResponseMeta) {
	o.Meta = &v
}

func (o ListGames200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGames200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableListGames200Response struct {
	value *ListGames200Response
	isSet bool
}

func (v NullableListGames200Response) Get() *ListGames200Response {
	return v.value
}

func (v *NullableListGames200Response) Set(val *ListGames200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListGames200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListGames200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGames200Response(val *ListGames200Response) *NullableListGames200Response {
	return &NullableListGames200Response{value: val, isSet: true}
}

func (v NullableListGames200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGames200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


