/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListGames200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGames200ResponseDataInner{}

// ListGames200ResponseDataInner struct for ListGames200ResponseDataInner
type ListGames200ResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
	Producer *string `json:"producer,omitempty"`
	Category *string `json:"category,omitempty"`
	Type *string `json:"type,omitempty"`
	ImageUrl *string `json:"image_url,omitempty"`
	CurrenciesSupported []string `json:"currencies_supported,omitempty"`
	CountriesSupported []string `json:"countries_supported,omitempty"`
	HasDemo *bool `json:"has_demo,omitempty"`
	HasFreespins *bool `json:"has_freespins,omitempty"`
}

// NewListGames200ResponseDataInner instantiates a new ListGames200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGames200ResponseDataInner() *ListGames200ResponseDataInner {
	this := ListGames200ResponseDataInner{}
	return &this
}

// NewListGames200ResponseDataInnerWithDefaults instantiates a new ListGames200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGames200ResponseDataInnerWithDefaults() *ListGames200ResponseDataInner {
	this := ListGames200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ListGames200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ListGames200ResponseDataInner) SetTitle(v string) {
	o.Title = &v
}

// GetProducer returns the Producer field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetProducer() string {
	if o == nil || IsNil(o.Producer) {
		var ret string
		return ret
	}
	return *o.Producer
}

// GetProducerOk returns a tuple with the Producer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetProducerOk() (*string, bool) {
	if o == nil || IsNil(o.Producer) {
		return nil, false
	}
	return o.Producer, true
}

// HasProducer returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasProducer() bool {
	if o != nil && !IsNil(o.Producer) {
		return true
	}

	return false
}

// SetProducer gets a reference to the given string and assigns it to the Producer field.
func (o *ListGames200ResponseDataInner) SetProducer(v string) {
	o.Producer = &v
}

// GetCategory returns the Category field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetCategory() string {
	if o == nil || IsNil(o.Category) {
		var ret string
		return ret
	}
	return *o.Category
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetCategoryOk() (*string, bool) {
	if o == nil || IsNil(o.Category) {
		return nil, false
	}
	return o.Category, true
}

// HasCategory returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasCategory() bool {
	if o != nil && !IsNil(o.Category) {
		return true
	}

	return false
}

// SetCategory gets a reference to the given string and assigns it to the Category field.
func (o *ListGames200ResponseDataInner) SetCategory(v string) {
	o.Category = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ListGames200ResponseDataInner) SetType(v string) {
	o.Type = &v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl) {
		var ret string
		return ret
	}
	return *o.ImageUrl
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetImageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.ImageUrl) {
		return nil, false
	}
	return o.ImageUrl, true
}

// HasImageUrl returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasImageUrl() bool {
	if o != nil && !IsNil(o.ImageUrl) {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given string and assigns it to the ImageUrl field.
func (o *ListGames200ResponseDataInner) SetImageUrl(v string) {
	o.ImageUrl = &v
}

// GetCurrenciesSupported returns the CurrenciesSupported field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetCurrenciesSupported() []string {
	if o == nil || IsNil(o.CurrenciesSupported) {
		var ret []string
		return ret
	}
	return o.CurrenciesSupported
}

// GetCurrenciesSupportedOk returns a tuple with the CurrenciesSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetCurrenciesSupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.CurrenciesSupported) {
		return nil, false
	}
	return o.CurrenciesSupported, true
}

// HasCurrenciesSupported returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasCurrenciesSupported() bool {
	if o != nil && !IsNil(o.CurrenciesSupported) {
		return true
	}

	return false
}

// SetCurrenciesSupported gets a reference to the given []string and assigns it to the CurrenciesSupported field.
func (o *ListGames200ResponseDataInner) SetCurrenciesSupported(v []string) {
	o.CurrenciesSupported = v
}

// GetCountriesSupported returns the CountriesSupported field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetCountriesSupported() []string {
	if o == nil || IsNil(o.CountriesSupported) {
		var ret []string
		return ret
	}
	return o.CountriesSupported
}

// GetCountriesSupportedOk returns a tuple with the CountriesSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetCountriesSupportedOk() ([]string, bool) {
	if o == nil || IsNil(o.CountriesSupported) {
		return nil, false
	}
	return o.CountriesSupported, true
}

// HasCountriesSupported returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasCountriesSupported() bool {
	if o != nil && !IsNil(o.CountriesSupported) {
		return true
	}

	return false
}

// SetCountriesSupported gets a reference to the given []string and assigns it to the CountriesSupported field.
func (o *ListGames200ResponseDataInner) SetCountriesSupported(v []string) {
	o.CountriesSupported = v
}

// GetHasDemo returns the HasDemo field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetHasDemo() bool {
	if o == nil || IsNil(o.HasDemo) {
		var ret bool
		return ret
	}
	return *o.HasDemo
}

// GetHasDemoOk returns a tuple with the HasDemo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetHasDemoOk() (*bool, bool) {
	if o == nil || IsNil(o.HasDemo) {
		return nil, false
	}
	return o.HasDemo, true
}

// HasHasDemo returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasHasDemo() bool {
	if o != nil && !IsNil(o.HasDemo) {
		return true
	}

	return false
}

// SetHasDemo gets a reference to the given bool and assigns it to the HasDemo field.
func (o *ListGames200ResponseDataInner) SetHasDemo(v bool) {
	o.HasDemo = &v
}

// GetHasFreespins returns the HasFreespins field value if set, zero value otherwise.
func (o *ListGames200ResponseDataInner) GetHasFreespins() bool {
	if o == nil || IsNil(o.HasFreespins) {
		var ret bool
		return ret
	}
	return *o.HasFreespins
}

// GetHasFreespinsOk returns a tuple with the HasFreespins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseDataInner) GetHasFreespinsOk() (*bool, bool) {
	if o == nil || IsNil(o.HasFreespins) {
		return nil, false
	}
	return o.HasFreespins, true
}

// HasHasFreespins returns a boolean if a field has been set.
func (o *ListGames200ResponseDataInner) HasHasFreespins() bool {
	if o != nil && !IsNil(o.HasFreespins) {
		return true
	}

	return false
}

// SetHasFreespins gets a reference to the given bool and assigns it to the HasFreespins field.
func (o *ListGames200ResponseDataInner) SetHasFreespins(v bool) {
	o.HasFreespins = &v
}

func (o ListGames200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGames200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Producer) {
		toSerialize["producer"] = o.Producer
	}
	if !IsNil(o.Category) {
		toSerialize["category"] = o.Category
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.ImageUrl) {
		toSerialize["image_url"] = o.ImageUrl
	}
	if !IsNil(o.CurrenciesSupported) {
		toSerialize["currencies_supported"] = o.CurrenciesSupported
	}
	if !IsNil(o.CountriesSupported) {
		toSerialize["countries_supported"] = o.CountriesSupported
	}
	if !IsNil(o.HasDemo) {
		toSerialize["has_demo"] = o.HasDemo
	}
	if !IsNil(o.HasFreespins) {
		toSerialize["has_freespins"] = o.HasFreespins
	}
	return toSerialize, nil
}

type NullableListGames200ResponseDataInner struct {
	value *ListGames200ResponseDataInner
	isSet bool
}

func (v NullableListGames200ResponseDataInner) Get() *ListGames200ResponseDataInner {
	return v.value
}

func (v *NullableListGames200ResponseDataInner) Set(val *ListGames200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListGames200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListGames200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGames200ResponseDataInner(val *ListGames200ResponseDataInner) *NullableListGames200ResponseDataInner {
	return &NullableListGames200ResponseDataInner{value: val, isSet: true}
}

func (v NullableListGames200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGames200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


