/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetGrandPrizeExpirationDateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetGrandPrizeExpirationDateRequest{}

// SetGrandPrizeExpirationDateRequest struct for SetGrandPrizeExpirationDateRequest
type SetGrandPrizeExpirationDateRequest struct {
	// Must be a valid date. Must be a date after <code>now</code>.
	ExpiresAt string `json:"expires_at"`
}

type _SetGrandPrizeExpirationDateRequest SetGrandPrizeExpirationDateRequest

// NewSetGrandPrizeExpirationDateRequest instantiates a new SetGrandPrizeExpirationDateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetGrandPrizeExpirationDateRequest(expiresAt string) *SetGrandPrizeExpirationDateRequest {
	this := SetGrandPrizeExpirationDateRequest{}
	this.ExpiresAt = expiresAt
	return &this
}

// NewSetGrandPrizeExpirationDateRequestWithDefaults instantiates a new SetGrandPrizeExpirationDateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetGrandPrizeExpirationDateRequestWithDefaults() *SetGrandPrizeExpirationDateRequest {
	this := SetGrandPrizeExpirationDateRequest{}
	return &this
}

// GetExpiresAt returns the ExpiresAt field value
func (o *SetGrandPrizeExpirationDateRequest) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *SetGrandPrizeExpirationDateRequest) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *SetGrandPrizeExpirationDateRequest) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

func (o SetGrandPrizeExpirationDateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetGrandPrizeExpirationDateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["expires_at"] = o.ExpiresAt
	return toSerialize, nil
}

func (o *SetGrandPrizeExpirationDateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"expires_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetGrandPrizeExpirationDateRequest := _SetGrandPrizeExpirationDateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetGrandPrizeExpirationDateRequest)

	if err != nil {
		return err
	}

	*o = SetGrandPrizeExpirationDateRequest(varSetGrandPrizeExpirationDateRequest)

	return err
}

type NullableSetGrandPrizeExpirationDateRequest struct {
	value *SetGrandPrizeExpirationDateRequest
	isSet bool
}

func (v NullableSetGrandPrizeExpirationDateRequest) Get() *SetGrandPrizeExpirationDateRequest {
	return v.value
}

func (v *NullableSetGrandPrizeExpirationDateRequest) Set(val *SetGrandPrizeExpirationDateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetGrandPrizeExpirationDateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetGrandPrizeExpirationDateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetGrandPrizeExpirationDateRequest(val *SetGrandPrizeExpirationDateRequest) *NullableSetGrandPrizeExpirationDateRequest {
	return &NullableSetGrandPrizeExpirationDateRequest{value: val, isSet: true}
}

func (v NullableSetGrandPrizeExpirationDateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetGrandPrizeExpirationDateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


