/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StartAGameSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartAGameSessionRequest{}

// StartAGameSessionRequest struct for StartAGameSessionRequest
type StartAGameSessionRequest struct {
	// The ID of the game to start.
	GameId int32 `json:"game_id"`
	// The player's ID in your system.
	PlayerId string `json:"player_id"`
	// Three-letter currency code (ISO 4217).
	Currency string `json:"currency"`
	// The player's IP address.
	IpAddress string `json:"ip_address"`
	// Two-letter country code (ISO 3166-1 alpha-2).
	CountryCode string `json:"country_code"`
	// optional URL to redirect the player after game ends.
	ReturnUrl NullableString `json:"return_url,omitempty"`
	// optional Player's language preference (ISO 639-1).
	Locale NullableString `json:"locale,omitempty"`
	// optional Provider slug to use for this session. Requires can_override_provider enabled.
	Provider NullableString `json:"provider,omitempty"`
	// optional Free spin bonus ID.
	FreespinId NullableString `json:"freespin_id,omitempty"`
	// optional Number of free spins.
	FreespinCount NullableInt32 `json:"freespin_count,omitempty"`
	// optional Bet amount per free spin.
	FreespinBetAmount NullableNumeric `json:"freespin_bet_amount,omitempty"`
	// optional Free spin expiration in days (1-30).
	ExpireDays NullableInt32 `json:"expire_days,omitempty"`
	// optional Device type (desktop, mobile).
	Device NullableString `json:"device,omitempty"`
}

type _StartAGameSessionRequest StartAGameSessionRequest

// NewStartAGameSessionRequest instantiates a new StartAGameSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartAGameSessionRequest(gameId int32, playerId string, currency string, ipAddress string, countryCode string) *StartAGameSessionRequest {
	this := StartAGameSessionRequest{}
	this.GameId = gameId
	this.PlayerId = playerId
	this.Currency = currency
	this.IpAddress = ipAddress
	this.CountryCode = countryCode
	return &this
}

// NewStartAGameSessionRequestWithDefaults instantiates a new StartAGameSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartAGameSessionRequestWithDefaults() *StartAGameSessionRequest {
	this := StartAGameSessionRequest{}
	return &this
}

// GetGameId returns the GameId field value
func (o *StartAGameSessionRequest) GetGameId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.GameId
}

// GetGameIdOk returns a tuple with the GameId field value
// and a boolean to check if the value has been set.
func (o *StartAGameSessionRequest) GetGameIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.GameId, true
}

// SetGameId sets field value
func (o *StartAGameSessionRequest) SetGameId(v int32) {
	o.GameId = v
}

// GetPlayerId returns the PlayerId field value
func (o *StartAGameSessionRequest) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *StartAGameSessionRequest) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *StartAGameSessionRequest) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetCurrency returns the Currency field value
func (o *StartAGameSessionRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *StartAGameSessionRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *StartAGameSessionRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetIpAddress returns the IpAddress field value
func (o *StartAGameSessionRequest) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *StartAGameSessionRequest) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *StartAGameSessionRequest) SetIpAddress(v string) {
	o.IpAddress = v
}

// GetCountryCode returns the CountryCode field value
func (o *StartAGameSessionRequest) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *StartAGameSessionRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *StartAGameSessionRequest) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetReturnUrl returns the ReturnUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetReturnUrl() string {
	if o == nil || IsNil(o.ReturnUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ReturnUrl.Get()
}

// GetReturnUrlOk returns a tuple with the ReturnUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetReturnUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReturnUrl.Get(), o.ReturnUrl.IsSet()
}

// HasReturnUrl returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasReturnUrl() bool {
	if o != nil && o.ReturnUrl.IsSet() {
		return true
	}

	return false
}

// SetReturnUrl gets a reference to the given NullableString and assigns it to the ReturnUrl field.
func (o *StartAGameSessionRequest) SetReturnUrl(v string) {
	o.ReturnUrl.Set(&v)
}
// SetReturnUrlNil sets the value for ReturnUrl to be an explicit nil
func (o *StartAGameSessionRequest) SetReturnUrlNil() {
	o.ReturnUrl.Set(nil)
}

// UnsetReturnUrl ensures that no value is present for ReturnUrl, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetReturnUrl() {
	o.ReturnUrl.Unset()
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *StartAGameSessionRequest) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *StartAGameSessionRequest) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetLocale() {
	o.Locale.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *StartAGameSessionRequest) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *StartAGameSessionRequest) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetProvider() {
	o.Provider.Unset()
}

// GetFreespinId returns the FreespinId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetFreespinId() string {
	if o == nil || IsNil(o.FreespinId.Get()) {
		var ret string
		return ret
	}
	return *o.FreespinId.Get()
}

// GetFreespinIdOk returns a tuple with the FreespinId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetFreespinIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FreespinId.Get(), o.FreespinId.IsSet()
}

// HasFreespinId returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasFreespinId() bool {
	if o != nil && o.FreespinId.IsSet() {
		return true
	}

	return false
}

// SetFreespinId gets a reference to the given NullableString and assigns it to the FreespinId field.
func (o *StartAGameSessionRequest) SetFreespinId(v string) {
	o.FreespinId.Set(&v)
}
// SetFreespinIdNil sets the value for FreespinId to be an explicit nil
func (o *StartAGameSessionRequest) SetFreespinIdNil() {
	o.FreespinId.Set(nil)
}

// UnsetFreespinId ensures that no value is present for FreespinId, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetFreespinId() {
	o.FreespinId.Unset()
}

// GetFreespinCount returns the FreespinCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetFreespinCount() int32 {
	if o == nil || IsNil(o.FreespinCount.Get()) {
		var ret int32
		return ret
	}
	return *o.FreespinCount.Get()
}

// GetFreespinCountOk returns a tuple with the FreespinCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetFreespinCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.FreespinCount.Get(), o.FreespinCount.IsSet()
}

// HasFreespinCount returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasFreespinCount() bool {
	if o != nil && o.FreespinCount.IsSet() {
		return true
	}

	return false
}

// SetFreespinCount gets a reference to the given NullableInt32 and assigns it to the FreespinCount field.
func (o *StartAGameSessionRequest) SetFreespinCount(v int32) {
	o.FreespinCount.Set(&v)
}
// SetFreespinCountNil sets the value for FreespinCount to be an explicit nil
func (o *StartAGameSessionRequest) SetFreespinCountNil() {
	o.FreespinCount.Set(nil)
}

// UnsetFreespinCount ensures that no value is present for FreespinCount, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetFreespinCount() {
	o.FreespinCount.Unset()
}

// GetFreespinBetAmount returns the FreespinBetAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetFreespinBetAmount() Numeric {
	if o == nil || IsNil(o.FreespinBetAmount.Get()) {
		var ret Numeric
		return ret
	}
	return *o.FreespinBetAmount.Get()
}

// GetFreespinBetAmountOk returns a tuple with the FreespinBetAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetFreespinBetAmountOk() (*Numeric, bool) {
	if o == nil {
		return nil, false
	}
	return o.FreespinBetAmount.Get(), o.FreespinBetAmount.IsSet()
}

// HasFreespinBetAmount returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasFreespinBetAmount() bool {
	if o != nil && o.FreespinBetAmount.IsSet() {
		return true
	}

	return false
}

// SetFreespinBetAmount gets a reference to the given NullableNumeric and assigns it to the FreespinBetAmount field.
func (o *StartAGameSessionRequest) SetFreespinBetAmount(v Numeric) {
	o.FreespinBetAmount.Set(&v)
}
// SetFreespinBetAmountNil sets the value for FreespinBetAmount to be an explicit nil
func (o *StartAGameSessionRequest) SetFreespinBetAmountNil() {
	o.FreespinBetAmount.Set(nil)
}

// UnsetFreespinBetAmount ensures that no value is present for FreespinBetAmount, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetFreespinBetAmount() {
	o.FreespinBetAmount.Unset()
}

// GetExpireDays returns the ExpireDays field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetExpireDays() int32 {
	if o == nil || IsNil(o.ExpireDays.Get()) {
		var ret int32
		return ret
	}
	return *o.ExpireDays.Get()
}

// GetExpireDaysOk returns a tuple with the ExpireDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetExpireDaysOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpireDays.Get(), o.ExpireDays.IsSet()
}

// HasExpireDays returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasExpireDays() bool {
	if o != nil && o.ExpireDays.IsSet() {
		return true
	}

	return false
}

// SetExpireDays gets a reference to the given NullableInt32 and assigns it to the ExpireDays field.
func (o *StartAGameSessionRequest) SetExpireDays(v int32) {
	o.ExpireDays.Set(&v)
}
// SetExpireDaysNil sets the value for ExpireDays to be an explicit nil
func (o *StartAGameSessionRequest) SetExpireDaysNil() {
	o.ExpireDays.Set(nil)
}

// UnsetExpireDays ensures that no value is present for ExpireDays, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetExpireDays() {
	o.ExpireDays.Unset()
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAGameSessionRequest) GetDevice() string {
	if o == nil || IsNil(o.Device.Get()) {
		var ret string
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAGameSessionRequest) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *StartAGameSessionRequest) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableString and assigns it to the Device field.
func (o *StartAGameSessionRequest) SetDevice(v string) {
	o.Device.Set(&v)
}
// SetDeviceNil sets the value for Device to be an explicit nil
func (o *StartAGameSessionRequest) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *StartAGameSessionRequest) UnsetDevice() {
	o.Device.Unset()
}

func (o StartAGameSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartAGameSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["game_id"] = o.GameId
	toSerialize["player_id"] = o.PlayerId
	toSerialize["currency"] = o.Currency
	toSerialize["ip_address"] = o.IpAddress
	toSerialize["country_code"] = o.CountryCode
	if o.ReturnUrl.IsSet() {
		toSerialize["return_url"] = o.ReturnUrl.Get()
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.FreespinId.IsSet() {
		toSerialize["freespin_id"] = o.FreespinId.Get()
	}
	if o.FreespinCount.IsSet() {
		toSerialize["freespin_count"] = o.FreespinCount.Get()
	}
	if o.FreespinBetAmount.IsSet() {
		toSerialize["freespin_bet_amount"] = o.FreespinBetAmount.Get()
	}
	if o.ExpireDays.IsSet() {
		toSerialize["expire_days"] = o.ExpireDays.Get()
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	return toSerialize, nil
}

func (o *StartAGameSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"game_id",
		"player_id",
		"currency",
		"ip_address",
		"country_code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStartAGameSessionRequest := _StartAGameSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStartAGameSessionRequest)

	if err != nil {
		return err
	}

	*o = StartAGameSessionRequest(varStartAGameSessionRequest)

	return err
}

type NullableStartAGameSessionRequest struct {
	value *StartAGameSessionRequest
	isSet bool
}

func (v NullableStartAGameSessionRequest) Get() *StartAGameSessionRequest {
	return v.value
}

func (v *NullableStartAGameSessionRequest) Set(val *StartAGameSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartAGameSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartAGameSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartAGameSessionRequest(val *StartAGameSessionRequest) *NullableStartAGameSessionRequest {
	return &NullableStartAGameSessionRequest{value: val, isSet: true}
}

func (v NullableStartAGameSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartAGameSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


