/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the RegisterANewDomain201ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegisterANewDomain201ResponseData{}

// RegisterANewDomain201ResponseData struct for RegisterANewDomain201ResponseData
type RegisterANewDomain201ResponseData struct {
	Id *int32 `json:"id,omitempty"`
	Domain *string `json:"domain,omitempty"`
	DomainToken *string `json:"domain_token,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	AllowedWidgets []string `json:"allowed_widgets,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// NewRegisterANewDomain201ResponseData instantiates a new RegisterANewDomain201ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegisterANewDomain201ResponseData() *RegisterANewDomain201ResponseData {
	this := RegisterANewDomain201ResponseData{}
	return &this
}

// NewRegisterANewDomain201ResponseDataWithDefaults instantiates a new RegisterANewDomain201ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegisterANewDomain201ResponseDataWithDefaults() *RegisterANewDomain201ResponseData {
	this := RegisterANewDomain201ResponseData{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RegisterANewDomain201ResponseData) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomain201ResponseData) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RegisterANewDomain201ResponseData) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *RegisterANewDomain201ResponseData) SetId(v int32) {
	o.Id = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *RegisterANewDomain201ResponseData) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomain201ResponseData) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *RegisterANewDomain201ResponseData) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *RegisterANewDomain201ResponseData) SetDomain(v string) {
	o.Domain = &v
}

// GetDomainToken returns the DomainToken field value if set, zero value otherwise.
func (o *RegisterANewDomain201ResponseData) GetDomainToken() string {
	if o == nil || IsNil(o.DomainToken) {
		var ret string
		return ret
	}
	return *o.DomainToken
}

// GetDomainTokenOk returns a tuple with the DomainToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomain201ResponseData) GetDomainTokenOk() (*string, bool) {
	if o == nil || IsNil(o.DomainToken) {
		return nil, false
	}
	return o.DomainToken, true
}

// HasDomainToken returns a boolean if a field has been set.
func (o *RegisterANewDomain201ResponseData) HasDomainToken() bool {
	if o != nil && !IsNil(o.DomainToken) {
		return true
	}

	return false
}

// SetDomainToken gets a reference to the given string and assigns it to the DomainToken field.
func (o *RegisterANewDomain201ResponseData) SetDomainToken(v string) {
	o.DomainToken = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *RegisterANewDomain201ResponseData) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomain201ResponseData) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *RegisterANewDomain201ResponseData) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *RegisterANewDomain201ResponseData) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetAllowedWidgets returns the AllowedWidgets field value if set, zero value otherwise.
func (o *RegisterANewDomain201ResponseData) GetAllowedWidgets() []string {
	if o == nil || IsNil(o.AllowedWidgets) {
		var ret []string
		return ret
	}
	return o.AllowedWidgets
}

// GetAllowedWidgetsOk returns a tuple with the AllowedWidgets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomain201ResponseData) GetAllowedWidgetsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedWidgets) {
		return nil, false
	}
	return o.AllowedWidgets, true
}

// HasAllowedWidgets returns a boolean if a field has been set.
func (o *RegisterANewDomain201ResponseData) HasAllowedWidgets() bool {
	if o != nil && !IsNil(o.AllowedWidgets) {
		return true
	}

	return false
}

// SetAllowedWidgets gets a reference to the given []string and assigns it to the AllowedWidgets field.
func (o *RegisterANewDomain201ResponseData) SetAllowedWidgets(v []string) {
	o.AllowedWidgets = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *RegisterANewDomain201ResponseData) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegisterANewDomain201ResponseData) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *RegisterANewDomain201ResponseData) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *RegisterANewDomain201ResponseData) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o RegisterANewDomain201ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegisterANewDomain201ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.DomainToken) {
		toSerialize["domain_token"] = o.DomainToken
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.AllowedWidgets) {
		toSerialize["allowed_widgets"] = o.AllowedWidgets
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableRegisterANewDomain201ResponseData struct {
	value *RegisterANewDomain201ResponseData
	isSet bool
}

func (v NullableRegisterANewDomain201ResponseData) Get() *RegisterANewDomain201ResponseData {
	return v.value
}

func (v *NullableRegisterANewDomain201ResponseData) Set(val *RegisterANewDomain201ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegisterANewDomain201ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegisterANewDomain201ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegisterANewDomain201ResponseData(val *RegisterANewDomain201ResponseData) *NullableRegisterANewDomain201ResponseData {
	return &NullableRegisterANewDomain201ResponseData{value: val, isSet: true}
}

func (v NullableRegisterANewDomain201ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegisterANewDomain201ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


