/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListWidgetTokens200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListWidgetTokens200ResponseDataInner{}

// ListWidgetTokens200ResponseDataInner struct for ListWidgetTokens200ResponseDataInner
type ListWidgetTokens200ResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	Domain *string `json:"domain,omitempty"`
	WidgetType *string `json:"widget_type,omitempty"`
	PlayerId *string `json:"player_id,omitempty"`
	Currency *string `json:"currency,omitempty"`
	AllowedPoolTypes []string `json:"allowed_pool_types,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	LastUsedAt *string `json:"last_used_at,omitempty"`
	RequestCount *int32 `json:"request_count,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// NewListWidgetTokens200ResponseDataInner instantiates a new ListWidgetTokens200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListWidgetTokens200ResponseDataInner() *ListWidgetTokens200ResponseDataInner {
	this := ListWidgetTokens200ResponseDataInner{}
	return &this
}

// NewListWidgetTokens200ResponseDataInnerWithDefaults instantiates a new ListWidgetTokens200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListWidgetTokens200ResponseDataInnerWithDefaults() *ListWidgetTokens200ResponseDataInner {
	this := ListWidgetTokens200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ListWidgetTokens200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *ListWidgetTokens200ResponseDataInner) SetDomain(v string) {
	o.Domain = &v
}

// GetWidgetType returns the WidgetType field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetWidgetType() string {
	if o == nil || IsNil(o.WidgetType) {
		var ret string
		return ret
	}
	return *o.WidgetType
}

// GetWidgetTypeOk returns a tuple with the WidgetType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetWidgetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.WidgetType) {
		return nil, false
	}
	return o.WidgetType, true
}

// HasWidgetType returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasWidgetType() bool {
	if o != nil && !IsNil(o.WidgetType) {
		return true
	}

	return false
}

// SetWidgetType gets a reference to the given string and assigns it to the WidgetType field.
func (o *ListWidgetTokens200ResponseDataInner) SetWidgetType(v string) {
	o.WidgetType = &v
}

// GetPlayerId returns the PlayerId field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetPlayerId() string {
	if o == nil || IsNil(o.PlayerId) {
		var ret string
		return ret
	}
	return *o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetPlayerIdOk() (*string, bool) {
	if o == nil || IsNil(o.PlayerId) {
		return nil, false
	}
	return o.PlayerId, true
}

// HasPlayerId returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasPlayerId() bool {
	if o != nil && !IsNil(o.PlayerId) {
		return true
	}

	return false
}

// SetPlayerId gets a reference to the given string and assigns it to the PlayerId field.
func (o *ListWidgetTokens200ResponseDataInner) SetPlayerId(v string) {
	o.PlayerId = &v
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetCurrency() string {
	if o == nil || IsNil(o.Currency) {
		var ret string
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given string and assigns it to the Currency field.
func (o *ListWidgetTokens200ResponseDataInner) SetCurrency(v string) {
	o.Currency = &v
}

// GetAllowedPoolTypes returns the AllowedPoolTypes field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetAllowedPoolTypes() []string {
	if o == nil || IsNil(o.AllowedPoolTypes) {
		var ret []string
		return ret
	}
	return o.AllowedPoolTypes
}

// GetAllowedPoolTypesOk returns a tuple with the AllowedPoolTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetAllowedPoolTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedPoolTypes) {
		return nil, false
	}
	return o.AllowedPoolTypes, true
}

// HasAllowedPoolTypes returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasAllowedPoolTypes() bool {
	if o != nil && !IsNil(o.AllowedPoolTypes) {
		return true
	}

	return false
}

// SetAllowedPoolTypes gets a reference to the given []string and assigns it to the AllowedPoolTypes field.
func (o *ListWidgetTokens200ResponseDataInner) SetAllowedPoolTypes(v []string) {
	o.AllowedPoolTypes = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *ListWidgetTokens200ResponseDataInner) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetExpiresAt() string {
	if o == nil || IsNil(o.ExpiresAt) {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetExpiresAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiresAt) {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasExpiresAt() bool {
	if o != nil && !IsNil(o.ExpiresAt) {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *ListWidgetTokens200ResponseDataInner) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetLastUsedAt() string {
	if o == nil || IsNil(o.LastUsedAt) {
		var ret string
		return ret
	}
	return *o.LastUsedAt
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetLastUsedAtOk() (*string, bool) {
	if o == nil || IsNil(o.LastUsedAt) {
		return nil, false
	}
	return o.LastUsedAt, true
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasLastUsedAt() bool {
	if o != nil && !IsNil(o.LastUsedAt) {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given string and assigns it to the LastUsedAt field.
func (o *ListWidgetTokens200ResponseDataInner) SetLastUsedAt(v string) {
	o.LastUsedAt = &v
}

// GetRequestCount returns the RequestCount field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetRequestCount() int32 {
	if o == nil || IsNil(o.RequestCount) {
		var ret int32
		return ret
	}
	return *o.RequestCount
}

// GetRequestCountOk returns a tuple with the RequestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetRequestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RequestCount) {
		return nil, false
	}
	return o.RequestCount, true
}

// HasRequestCount returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasRequestCount() bool {
	if o != nil && !IsNil(o.RequestCount) {
		return true
	}

	return false
}

// SetRequestCount gets a reference to the given int32 and assigns it to the RequestCount field.
func (o *ListWidgetTokens200ResponseDataInner) SetRequestCount(v int32) {
	o.RequestCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListWidgetTokens200ResponseDataInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListWidgetTokens200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListWidgetTokens200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ListWidgetTokens200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o ListWidgetTokens200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListWidgetTokens200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.WidgetType) {
		toSerialize["widget_type"] = o.WidgetType
	}
	if !IsNil(o.PlayerId) {
		toSerialize["player_id"] = o.PlayerId
	}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.AllowedPoolTypes) {
		toSerialize["allowed_pool_types"] = o.AllowedPoolTypes
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.ExpiresAt) {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if !IsNil(o.LastUsedAt) {
		toSerialize["last_used_at"] = o.LastUsedAt
	}
	if !IsNil(o.RequestCount) {
		toSerialize["request_count"] = o.RequestCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableListWidgetTokens200ResponseDataInner struct {
	value *ListWidgetTokens200ResponseDataInner
	isSet bool
}

func (v NullableListWidgetTokens200ResponseDataInner) Get() *ListWidgetTokens200ResponseDataInner {
	return v.value
}

func (v *NullableListWidgetTokens200ResponseDataInner) Set(val *ListWidgetTokens200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListWidgetTokens200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListWidgetTokens200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListWidgetTokens200ResponseDataInner(val *ListWidgetTokens200ResponseDataInner) *NullableListWidgetTokens200ResponseDataInner {
	return &NullableListWidgetTokens200ResponseDataInner{value: val, isSet: true}
}

func (v NullableListWidgetTokens200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListWidgetTokens200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


