/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListGamesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGamesRequest{}

// ListGamesRequest struct for ListGamesRequest
type ListGamesRequest struct {
	// Must not be greater than 255 characters.
	Search NullableString `json:"search,omitempty"`
	// The <code>id</code> of an existing record in the game_producers table.
	ProducerId NullableInt32 `json:"producer_id,omitempty"`
	// The <code>slug</code> of an existing record in the providers table.
	Provider NullableString `json:"provider,omitempty"`
	// 
	Type NullableString `json:"type,omitempty"`
	// Must match the regex /^(all.
	PerPage NullableString `json:"per_page,omitempty"`
}

// NewListGamesRequest instantiates a new ListGamesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGamesRequest() *ListGamesRequest {
	this := ListGamesRequest{}
	return &this
}

// NewListGamesRequestWithDefaults instantiates a new ListGamesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGamesRequestWithDefaults() *ListGamesRequest {
	this := ListGamesRequest{}
	return &this
}

// GetSearch returns the Search field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGamesRequest) GetSearch() string {
	if o == nil || IsNil(o.Search.Get()) {
		var ret string
		return ret
	}
	return *o.Search.Get()
}

// GetSearchOk returns a tuple with the Search field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGamesRequest) GetSearchOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Search.Get(), o.Search.IsSet()
}

// HasSearch returns a boolean if a field has been set.
func (o *ListGamesRequest) HasSearch() bool {
	if o != nil && o.Search.IsSet() {
		return true
	}

	return false
}

// SetSearch gets a reference to the given NullableString and assigns it to the Search field.
func (o *ListGamesRequest) SetSearch(v string) {
	o.Search.Set(&v)
}
// SetSearchNil sets the value for Search to be an explicit nil
func (o *ListGamesRequest) SetSearchNil() {
	o.Search.Set(nil)
}

// UnsetSearch ensures that no value is present for Search, not even an explicit nil
func (o *ListGamesRequest) UnsetSearch() {
	o.Search.Unset()
}

// GetProducerId returns the ProducerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGamesRequest) GetProducerId() int32 {
	if o == nil || IsNil(o.ProducerId.Get()) {
		var ret int32
		return ret
	}
	return *o.ProducerId.Get()
}

// GetProducerIdOk returns a tuple with the ProducerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGamesRequest) GetProducerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProducerId.Get(), o.ProducerId.IsSet()
}

// HasProducerId returns a boolean if a field has been set.
func (o *ListGamesRequest) HasProducerId() bool {
	if o != nil && o.ProducerId.IsSet() {
		return true
	}

	return false
}

// SetProducerId gets a reference to the given NullableInt32 and assigns it to the ProducerId field.
func (o *ListGamesRequest) SetProducerId(v int32) {
	o.ProducerId.Set(&v)
}
// SetProducerIdNil sets the value for ProducerId to be an explicit nil
func (o *ListGamesRequest) SetProducerIdNil() {
	o.ProducerId.Set(nil)
}

// UnsetProducerId ensures that no value is present for ProducerId, not even an explicit nil
func (o *ListGamesRequest) UnsetProducerId() {
	o.ProducerId.Unset()
}

// GetProvider returns the Provider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGamesRequest) GetProvider() string {
	if o == nil || IsNil(o.Provider.Get()) {
		var ret string
		return ret
	}
	return *o.Provider.Get()
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGamesRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Provider.Get(), o.Provider.IsSet()
}

// HasProvider returns a boolean if a field has been set.
func (o *ListGamesRequest) HasProvider() bool {
	if o != nil && o.Provider.IsSet() {
		return true
	}

	return false
}

// SetProvider gets a reference to the given NullableString and assigns it to the Provider field.
func (o *ListGamesRequest) SetProvider(v string) {
	o.Provider.Set(&v)
}
// SetProviderNil sets the value for Provider to be an explicit nil
func (o *ListGamesRequest) SetProviderNil() {
	o.Provider.Set(nil)
}

// UnsetProvider ensures that no value is present for Provider, not even an explicit nil
func (o *ListGamesRequest) UnsetProvider() {
	o.Provider.Unset()
}

// GetType returns the Type field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGamesRequest) GetType() string {
	if o == nil || IsNil(o.Type.Get()) {
		var ret string
		return ret
	}
	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGamesRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// HasType returns a boolean if a field has been set.
func (o *ListGamesRequest) HasType() bool {
	if o != nil && o.Type.IsSet() {
		return true
	}

	return false
}

// SetType gets a reference to the given NullableString and assigns it to the Type field.
func (o *ListGamesRequest) SetType(v string) {
	o.Type.Set(&v)
}
// SetTypeNil sets the value for Type to be an explicit nil
func (o *ListGamesRequest) SetTypeNil() {
	o.Type.Set(nil)
}

// UnsetType ensures that no value is present for Type, not even an explicit nil
func (o *ListGamesRequest) UnsetType() {
	o.Type.Unset()
}

// GetPerPage returns the PerPage field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListGamesRequest) GetPerPage() string {
	if o == nil || IsNil(o.PerPage.Get()) {
		var ret string
		return ret
	}
	return *o.PerPage.Get()
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListGamesRequest) GetPerPageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PerPage.Get(), o.PerPage.IsSet()
}

// HasPerPage returns a boolean if a field has been set.
func (o *ListGamesRequest) HasPerPage() bool {
	if o != nil && o.PerPage.IsSet() {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given NullableString and assigns it to the PerPage field.
func (o *ListGamesRequest) SetPerPage(v string) {
	o.PerPage.Set(&v)
}
// SetPerPageNil sets the value for PerPage to be an explicit nil
func (o *ListGamesRequest) SetPerPageNil() {
	o.PerPage.Set(nil)
}

// UnsetPerPage ensures that no value is present for PerPage, not even an explicit nil
func (o *ListGamesRequest) UnsetPerPage() {
	o.PerPage.Unset()
}

func (o ListGamesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGamesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Search.IsSet() {
		toSerialize["search"] = o.Search.Get()
	}
	if o.ProducerId.IsSet() {
		toSerialize["producer_id"] = o.ProducerId.Get()
	}
	if o.Provider.IsSet() {
		toSerialize["provider"] = o.Provider.Get()
	}
	if o.Type.IsSet() {
		toSerialize["type"] = o.Type.Get()
	}
	if o.PerPage.IsSet() {
		toSerialize["per_page"] = o.PerPage.Get()
	}
	return toSerialize, nil
}

type NullableListGamesRequest struct {
	value *ListGamesRequest
	isSet bool
}

func (v NullableListGamesRequest) Get() *ListGamesRequest {
	return v.value
}

func (v *NullableListGamesRequest) Set(val *ListGamesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableListGamesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableListGamesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGamesRequest(val *ListGamesRequest) *NullableListGamesRequest {
	return &NullableListGamesRequest{value: val, isSet: true}
}

func (v NullableListGamesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGamesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


