/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddAContributionToAJackpotPoolRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddAContributionToAJackpotPoolRequest{}

// AddAContributionToAJackpotPoolRequest struct for AddAContributionToAJackpotPoolRequest
type AddAContributionToAJackpotPoolRequest struct {
	// Must not be greater than 100 characters.
	PlayerId string `json:"player_id"`
	// Must be 3 characters.
	Currency string `json:"currency"`
	// Must be at least 0.01. Must not be greater than 10000000.
	Amount float32 `json:"amount"`
	// Max 10 million per contribution.
	Type string `json:"type"`
	// Must not be greater than 255 characters.
	TransactionId string `json:"transaction_id"`
	// The <code>id</code> of an existing record in the games table.
	GameId NullableInt32 `json:"game_id,omitempty"`
	// Must not be greater than 100 characters.
	ExternalGameId NullableString `json:"external_game_id,omitempty"`
	// The <code>id</code> of an existing record in the game_sessions table.
	GameSessionId NullableInt32 `json:"game_session_id,omitempty"`
	// 
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _AddAContributionToAJackpotPoolRequest AddAContributionToAJackpotPoolRequest

// NewAddAContributionToAJackpotPoolRequest instantiates a new AddAContributionToAJackpotPoolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddAContributionToAJackpotPoolRequest(playerId string, currency string, amount float32, type_ string, transactionId string) *AddAContributionToAJackpotPoolRequest {
	this := AddAContributionToAJackpotPoolRequest{}
	this.PlayerId = playerId
	this.Currency = currency
	this.Amount = amount
	this.Type = type_
	this.TransactionId = transactionId
	return &this
}

// NewAddAContributionToAJackpotPoolRequestWithDefaults instantiates a new AddAContributionToAJackpotPoolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddAContributionToAJackpotPoolRequestWithDefaults() *AddAContributionToAJackpotPoolRequest {
	this := AddAContributionToAJackpotPoolRequest{}
	return &this
}

// GetPlayerId returns the PlayerId field value
func (o *AddAContributionToAJackpotPoolRequest) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *AddAContributionToAJackpotPoolRequest) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *AddAContributionToAJackpotPoolRequest) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetCurrency returns the Currency field value
func (o *AddAContributionToAJackpotPoolRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *AddAContributionToAJackpotPoolRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *AddAContributionToAJackpotPoolRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetAmount returns the Amount field value
func (o *AddAContributionToAJackpotPoolRequest) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AddAContributionToAJackpotPoolRequest) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AddAContributionToAJackpotPoolRequest) SetAmount(v float32) {
	o.Amount = v
}

// GetType returns the Type field value
func (o *AddAContributionToAJackpotPoolRequest) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *AddAContributionToAJackpotPoolRequest) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *AddAContributionToAJackpotPoolRequest) SetType(v string) {
	o.Type = v
}

// GetTransactionId returns the TransactionId field value
func (o *AddAContributionToAJackpotPoolRequest) GetTransactionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionId
}

// GetTransactionIdOk returns a tuple with the TransactionId field value
// and a boolean to check if the value has been set.
func (o *AddAContributionToAJackpotPoolRequest) GetTransactionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionId, true
}

// SetTransactionId sets field value
func (o *AddAContributionToAJackpotPoolRequest) SetTransactionId(v string) {
	o.TransactionId = v
}

// GetGameId returns the GameId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAContributionToAJackpotPoolRequest) GetGameId() int32 {
	if o == nil || IsNil(o.GameId.Get()) {
		var ret int32
		return ret
	}
	return *o.GameId.Get()
}

// GetGameIdOk returns a tuple with the GameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAContributionToAJackpotPoolRequest) GetGameIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GameId.Get(), o.GameId.IsSet()
}

// HasGameId returns a boolean if a field has been set.
func (o *AddAContributionToAJackpotPoolRequest) HasGameId() bool {
	if o != nil && o.GameId.IsSet() {
		return true
	}

	return false
}

// SetGameId gets a reference to the given NullableInt32 and assigns it to the GameId field.
func (o *AddAContributionToAJackpotPoolRequest) SetGameId(v int32) {
	o.GameId.Set(&v)
}
// SetGameIdNil sets the value for GameId to be an explicit nil
func (o *AddAContributionToAJackpotPoolRequest) SetGameIdNil() {
	o.GameId.Set(nil)
}

// UnsetGameId ensures that no value is present for GameId, not even an explicit nil
func (o *AddAContributionToAJackpotPoolRequest) UnsetGameId() {
	o.GameId.Unset()
}

// GetExternalGameId returns the ExternalGameId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAContributionToAJackpotPoolRequest) GetExternalGameId() string {
	if o == nil || IsNil(o.ExternalGameId.Get()) {
		var ret string
		return ret
	}
	return *o.ExternalGameId.Get()
}

// GetExternalGameIdOk returns a tuple with the ExternalGameId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAContributionToAJackpotPoolRequest) GetExternalGameIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExternalGameId.Get(), o.ExternalGameId.IsSet()
}

// HasExternalGameId returns a boolean if a field has been set.
func (o *AddAContributionToAJackpotPoolRequest) HasExternalGameId() bool {
	if o != nil && o.ExternalGameId.IsSet() {
		return true
	}

	return false
}

// SetExternalGameId gets a reference to the given NullableString and assigns it to the ExternalGameId field.
func (o *AddAContributionToAJackpotPoolRequest) SetExternalGameId(v string) {
	o.ExternalGameId.Set(&v)
}
// SetExternalGameIdNil sets the value for ExternalGameId to be an explicit nil
func (o *AddAContributionToAJackpotPoolRequest) SetExternalGameIdNil() {
	o.ExternalGameId.Set(nil)
}

// UnsetExternalGameId ensures that no value is present for ExternalGameId, not even an explicit nil
func (o *AddAContributionToAJackpotPoolRequest) UnsetExternalGameId() {
	o.ExternalGameId.Unset()
}

// GetGameSessionId returns the GameSessionId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAContributionToAJackpotPoolRequest) GetGameSessionId() int32 {
	if o == nil || IsNil(o.GameSessionId.Get()) {
		var ret int32
		return ret
	}
	return *o.GameSessionId.Get()
}

// GetGameSessionIdOk returns a tuple with the GameSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAContributionToAJackpotPoolRequest) GetGameSessionIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.GameSessionId.Get(), o.GameSessionId.IsSet()
}

// HasGameSessionId returns a boolean if a field has been set.
func (o *AddAContributionToAJackpotPoolRequest) HasGameSessionId() bool {
	if o != nil && o.GameSessionId.IsSet() {
		return true
	}

	return false
}

// SetGameSessionId gets a reference to the given NullableInt32 and assigns it to the GameSessionId field.
func (o *AddAContributionToAJackpotPoolRequest) SetGameSessionId(v int32) {
	o.GameSessionId.Set(&v)
}
// SetGameSessionIdNil sets the value for GameSessionId to be an explicit nil
func (o *AddAContributionToAJackpotPoolRequest) SetGameSessionIdNil() {
	o.GameSessionId.Set(nil)
}

// UnsetGameSessionId ensures that no value is present for GameSessionId, not even an explicit nil
func (o *AddAContributionToAJackpotPoolRequest) UnsetGameSessionId() {
	o.GameSessionId.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AddAContributionToAJackpotPoolRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AddAContributionToAJackpotPoolRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *AddAContributionToAJackpotPoolRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *AddAContributionToAJackpotPoolRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o AddAContributionToAJackpotPoolRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddAContributionToAJackpotPoolRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["player_id"] = o.PlayerId
	toSerialize["currency"] = o.Currency
	toSerialize["amount"] = o.Amount
	toSerialize["type"] = o.Type
	toSerialize["transaction_id"] = o.TransactionId
	if o.GameId.IsSet() {
		toSerialize["game_id"] = o.GameId.Get()
	}
	if o.ExternalGameId.IsSet() {
		toSerialize["external_game_id"] = o.ExternalGameId.Get()
	}
	if o.GameSessionId.IsSet() {
		toSerialize["game_session_id"] = o.GameSessionId.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *AddAContributionToAJackpotPoolRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"player_id",
		"currency",
		"amount",
		"type",
		"transaction_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddAContributionToAJackpotPoolRequest := _AddAContributionToAJackpotPoolRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddAContributionToAJackpotPoolRequest)

	if err != nil {
		return err
	}

	*o = AddAContributionToAJackpotPoolRequest(varAddAContributionToAJackpotPoolRequest)

	return err
}

type NullableAddAContributionToAJackpotPoolRequest struct {
	value *AddAContributionToAJackpotPoolRequest
	isSet bool
}

func (v NullableAddAContributionToAJackpotPoolRequest) Get() *AddAContributionToAJackpotPoolRequest {
	return v.value
}

func (v *NullableAddAContributionToAJackpotPoolRequest) Set(val *AddAContributionToAJackpotPoolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAddAContributionToAJackpotPoolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAddAContributionToAJackpotPoolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddAContributionToAJackpotPoolRequest(val *AddAContributionToAJackpotPoolRequest) *NullableAddAContributionToAJackpotPoolRequest {
	return &NullableAddAContributionToAJackpotPoolRequest{value: val, isSet: true}
}

func (v NullableAddAContributionToAJackpotPoolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddAContributionToAJackpotPoolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


