/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the UpdateAPromotionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAPromotionRequest{}

// UpdateAPromotionRequest struct for UpdateAPromotionRequest
type UpdateAPromotionRequest struct {
	// Must not be greater than 255 characters.
	Name *string `json:"name,omitempty"`
	// 
	Description NullableString `json:"description,omitempty"`
	// Must be a valid URL.
	ImageUrl NullableString `json:"image_url,omitempty"`
	// 
	TermsAndConditions NullableString `json:"terms_and_conditions,omitempty"`
	// Must be a valid date.
	EndsAt NullableString `json:"ends_at,omitempty"`
	// 
	PrizeDistribution map[string]interface{} `json:"prize_distribution,omitempty"`
	// Must be at least 0.
	TotalPrizePool NullableFloat32 `json:"total_prize_pool,omitempty"`
	// Must be at least 1.
	WinnerCount NullableInt32 `json:"winner_count,omitempty"`
	// 
	EntryConfig map[string]interface{} `json:"entry_config,omitempty"`
	// 
	GameFilterEnabled NullableBool `json:"game_filter_enabled,omitempty"`
	// 
	ProducerFilterEnabled NullableBool `json:"producer_filter_enabled,omitempty"`
	// 
	WebhookEnabled NullableBool `json:"webhook_enabled,omitempty"`
	// 
	IsActive NullableBool `json:"is_active,omitempty"`
	// 
	IsFeatured NullableBool `json:"is_featured,omitempty"`
}

// NewUpdateAPromotionRequest instantiates a new UpdateAPromotionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAPromotionRequest() *UpdateAPromotionRequest {
	this := UpdateAPromotionRequest{}
	return &this
}

// NewUpdateAPromotionRequestWithDefaults instantiates a new UpdateAPromotionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAPromotionRequestWithDefaults() *UpdateAPromotionRequest {
	this := UpdateAPromotionRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateAPromotionRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAPromotionRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateAPromotionRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *UpdateAPromotionRequest) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *UpdateAPromotionRequest) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetDescription() {
	o.Description.Unset()
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetImageUrl() string {
	if o == nil || IsNil(o.ImageUrl.Get()) {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetImageUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *UpdateAPromotionRequest) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}
// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *UpdateAPromotionRequest) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

// GetTermsAndConditions returns the TermsAndConditions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetTermsAndConditions() string {
	if o == nil || IsNil(o.TermsAndConditions.Get()) {
		var ret string
		return ret
	}
	return *o.TermsAndConditions.Get()
}

// GetTermsAndConditionsOk returns a tuple with the TermsAndConditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetTermsAndConditionsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TermsAndConditions.Get(), o.TermsAndConditions.IsSet()
}

// HasTermsAndConditions returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasTermsAndConditions() bool {
	if o != nil && o.TermsAndConditions.IsSet() {
		return true
	}

	return false
}

// SetTermsAndConditions gets a reference to the given NullableString and assigns it to the TermsAndConditions field.
func (o *UpdateAPromotionRequest) SetTermsAndConditions(v string) {
	o.TermsAndConditions.Set(&v)
}
// SetTermsAndConditionsNil sets the value for TermsAndConditions to be an explicit nil
func (o *UpdateAPromotionRequest) SetTermsAndConditionsNil() {
	o.TermsAndConditions.Set(nil)
}

// UnsetTermsAndConditions ensures that no value is present for TermsAndConditions, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetTermsAndConditions() {
	o.TermsAndConditions.Unset()
}

// GetEndsAt returns the EndsAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetEndsAt() string {
	if o == nil || IsNil(o.EndsAt.Get()) {
		var ret string
		return ret
	}
	return *o.EndsAt.Get()
}

// GetEndsAtOk returns a tuple with the EndsAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetEndsAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EndsAt.Get(), o.EndsAt.IsSet()
}

// HasEndsAt returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasEndsAt() bool {
	if o != nil && o.EndsAt.IsSet() {
		return true
	}

	return false
}

// SetEndsAt gets a reference to the given NullableString and assigns it to the EndsAt field.
func (o *UpdateAPromotionRequest) SetEndsAt(v string) {
	o.EndsAt.Set(&v)
}
// SetEndsAtNil sets the value for EndsAt to be an explicit nil
func (o *UpdateAPromotionRequest) SetEndsAtNil() {
	o.EndsAt.Set(nil)
}

// UnsetEndsAt ensures that no value is present for EndsAt, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetEndsAt() {
	o.EndsAt.Unset()
}

// GetPrizeDistribution returns the PrizeDistribution field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetPrizeDistribution() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.PrizeDistribution
}

// GetPrizeDistributionOk returns a tuple with the PrizeDistribution field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetPrizeDistributionOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.PrizeDistribution) {
		return map[string]interface{}{}, false
	}
	return o.PrizeDistribution, true
}

// HasPrizeDistribution returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasPrizeDistribution() bool {
	if o != nil && !IsNil(o.PrizeDistribution) {
		return true
	}

	return false
}

// SetPrizeDistribution gets a reference to the given map[string]interface{} and assigns it to the PrizeDistribution field.
func (o *UpdateAPromotionRequest) SetPrizeDistribution(v map[string]interface{}) {
	o.PrizeDistribution = v
}

// GetTotalPrizePool returns the TotalPrizePool field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetTotalPrizePool() float32 {
	if o == nil || IsNil(o.TotalPrizePool.Get()) {
		var ret float32
		return ret
	}
	return *o.TotalPrizePool.Get()
}

// GetTotalPrizePoolOk returns a tuple with the TotalPrizePool field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetTotalPrizePoolOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TotalPrizePool.Get(), o.TotalPrizePool.IsSet()
}

// HasTotalPrizePool returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasTotalPrizePool() bool {
	if o != nil && o.TotalPrizePool.IsSet() {
		return true
	}

	return false
}

// SetTotalPrizePool gets a reference to the given NullableFloat32 and assigns it to the TotalPrizePool field.
func (o *UpdateAPromotionRequest) SetTotalPrizePool(v float32) {
	o.TotalPrizePool.Set(&v)
}
// SetTotalPrizePoolNil sets the value for TotalPrizePool to be an explicit nil
func (o *UpdateAPromotionRequest) SetTotalPrizePoolNil() {
	o.TotalPrizePool.Set(nil)
}

// UnsetTotalPrizePool ensures that no value is present for TotalPrizePool, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetTotalPrizePool() {
	o.TotalPrizePool.Unset()
}

// GetWinnerCount returns the WinnerCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetWinnerCount() int32 {
	if o == nil || IsNil(o.WinnerCount.Get()) {
		var ret int32
		return ret
	}
	return *o.WinnerCount.Get()
}

// GetWinnerCountOk returns a tuple with the WinnerCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetWinnerCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.WinnerCount.Get(), o.WinnerCount.IsSet()
}

// HasWinnerCount returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasWinnerCount() bool {
	if o != nil && o.WinnerCount.IsSet() {
		return true
	}

	return false
}

// SetWinnerCount gets a reference to the given NullableInt32 and assigns it to the WinnerCount field.
func (o *UpdateAPromotionRequest) SetWinnerCount(v int32) {
	o.WinnerCount.Set(&v)
}
// SetWinnerCountNil sets the value for WinnerCount to be an explicit nil
func (o *UpdateAPromotionRequest) SetWinnerCountNil() {
	o.WinnerCount.Set(nil)
}

// UnsetWinnerCount ensures that no value is present for WinnerCount, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetWinnerCount() {
	o.WinnerCount.Unset()
}

// GetEntryConfig returns the EntryConfig field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetEntryConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.EntryConfig
}

// GetEntryConfigOk returns a tuple with the EntryConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetEntryConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.EntryConfig) {
		return map[string]interface{}{}, false
	}
	return o.EntryConfig, true
}

// HasEntryConfig returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasEntryConfig() bool {
	if o != nil && !IsNil(o.EntryConfig) {
		return true
	}

	return false
}

// SetEntryConfig gets a reference to the given map[string]interface{} and assigns it to the EntryConfig field.
func (o *UpdateAPromotionRequest) SetEntryConfig(v map[string]interface{}) {
	o.EntryConfig = v
}

// GetGameFilterEnabled returns the GameFilterEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetGameFilterEnabled() bool {
	if o == nil || IsNil(o.GameFilterEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.GameFilterEnabled.Get()
}

// GetGameFilterEnabledOk returns a tuple with the GameFilterEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetGameFilterEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.GameFilterEnabled.Get(), o.GameFilterEnabled.IsSet()
}

// HasGameFilterEnabled returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasGameFilterEnabled() bool {
	if o != nil && o.GameFilterEnabled.IsSet() {
		return true
	}

	return false
}

// SetGameFilterEnabled gets a reference to the given NullableBool and assigns it to the GameFilterEnabled field.
func (o *UpdateAPromotionRequest) SetGameFilterEnabled(v bool) {
	o.GameFilterEnabled.Set(&v)
}
// SetGameFilterEnabledNil sets the value for GameFilterEnabled to be an explicit nil
func (o *UpdateAPromotionRequest) SetGameFilterEnabledNil() {
	o.GameFilterEnabled.Set(nil)
}

// UnsetGameFilterEnabled ensures that no value is present for GameFilterEnabled, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetGameFilterEnabled() {
	o.GameFilterEnabled.Unset()
}

// GetProducerFilterEnabled returns the ProducerFilterEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetProducerFilterEnabled() bool {
	if o == nil || IsNil(o.ProducerFilterEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.ProducerFilterEnabled.Get()
}

// GetProducerFilterEnabledOk returns a tuple with the ProducerFilterEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetProducerFilterEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProducerFilterEnabled.Get(), o.ProducerFilterEnabled.IsSet()
}

// HasProducerFilterEnabled returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasProducerFilterEnabled() bool {
	if o != nil && o.ProducerFilterEnabled.IsSet() {
		return true
	}

	return false
}

// SetProducerFilterEnabled gets a reference to the given NullableBool and assigns it to the ProducerFilterEnabled field.
func (o *UpdateAPromotionRequest) SetProducerFilterEnabled(v bool) {
	o.ProducerFilterEnabled.Set(&v)
}
// SetProducerFilterEnabledNil sets the value for ProducerFilterEnabled to be an explicit nil
func (o *UpdateAPromotionRequest) SetProducerFilterEnabledNil() {
	o.ProducerFilterEnabled.Set(nil)
}

// UnsetProducerFilterEnabled ensures that no value is present for ProducerFilterEnabled, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetProducerFilterEnabled() {
	o.ProducerFilterEnabled.Unset()
}

// GetWebhookEnabled returns the WebhookEnabled field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetWebhookEnabled() bool {
	if o == nil || IsNil(o.WebhookEnabled.Get()) {
		var ret bool
		return ret
	}
	return *o.WebhookEnabled.Get()
}

// GetWebhookEnabledOk returns a tuple with the WebhookEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetWebhookEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.WebhookEnabled.Get(), o.WebhookEnabled.IsSet()
}

// HasWebhookEnabled returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasWebhookEnabled() bool {
	if o != nil && o.WebhookEnabled.IsSet() {
		return true
	}

	return false
}

// SetWebhookEnabled gets a reference to the given NullableBool and assigns it to the WebhookEnabled field.
func (o *UpdateAPromotionRequest) SetWebhookEnabled(v bool) {
	o.WebhookEnabled.Set(&v)
}
// SetWebhookEnabledNil sets the value for WebhookEnabled to be an explicit nil
func (o *UpdateAPromotionRequest) SetWebhookEnabledNil() {
	o.WebhookEnabled.Set(nil)
}

// UnsetWebhookEnabled ensures that no value is present for WebhookEnabled, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetWebhookEnabled() {
	o.WebhookEnabled.Unset()
}

// GetIsActive returns the IsActive field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive.Get()) {
		var ret bool
		return ret
	}
	return *o.IsActive.Get()
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsActive.Get(), o.IsActive.IsSet()
}

// HasIsActive returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasIsActive() bool {
	if o != nil && o.IsActive.IsSet() {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given NullableBool and assigns it to the IsActive field.
func (o *UpdateAPromotionRequest) SetIsActive(v bool) {
	o.IsActive.Set(&v)
}
// SetIsActiveNil sets the value for IsActive to be an explicit nil
func (o *UpdateAPromotionRequest) SetIsActiveNil() {
	o.IsActive.Set(nil)
}

// UnsetIsActive ensures that no value is present for IsActive, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetIsActive() {
	o.IsActive.Unset()
}

// GetIsFeatured returns the IsFeatured field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAPromotionRequest) GetIsFeatured() bool {
	if o == nil || IsNil(o.IsFeatured.Get()) {
		var ret bool
		return ret
	}
	return *o.IsFeatured.Get()
}

// GetIsFeaturedOk returns a tuple with the IsFeatured field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAPromotionRequest) GetIsFeaturedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsFeatured.Get(), o.IsFeatured.IsSet()
}

// HasIsFeatured returns a boolean if a field has been set.
func (o *UpdateAPromotionRequest) HasIsFeatured() bool {
	if o != nil && o.IsFeatured.IsSet() {
		return true
	}

	return false
}

// SetIsFeatured gets a reference to the given NullableBool and assigns it to the IsFeatured field.
func (o *UpdateAPromotionRequest) SetIsFeatured(v bool) {
	o.IsFeatured.Set(&v)
}
// SetIsFeaturedNil sets the value for IsFeatured to be an explicit nil
func (o *UpdateAPromotionRequest) SetIsFeaturedNil() {
	o.IsFeatured.Set(nil)
}

// UnsetIsFeatured ensures that no value is present for IsFeatured, not even an explicit nil
func (o *UpdateAPromotionRequest) UnsetIsFeatured() {
	o.IsFeatured.Unset()
}

func (o UpdateAPromotionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAPromotionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.ImageUrl.IsSet() {
		toSerialize["image_url"] = o.ImageUrl.Get()
	}
	if o.TermsAndConditions.IsSet() {
		toSerialize["terms_and_conditions"] = o.TermsAndConditions.Get()
	}
	if o.EndsAt.IsSet() {
		toSerialize["ends_at"] = o.EndsAt.Get()
	}
	if o.PrizeDistribution != nil {
		toSerialize["prize_distribution"] = o.PrizeDistribution
	}
	if o.TotalPrizePool.IsSet() {
		toSerialize["total_prize_pool"] = o.TotalPrizePool.Get()
	}
	if o.WinnerCount.IsSet() {
		toSerialize["winner_count"] = o.WinnerCount.Get()
	}
	if o.EntryConfig != nil {
		toSerialize["entry_config"] = o.EntryConfig
	}
	if o.GameFilterEnabled.IsSet() {
		toSerialize["game_filter_enabled"] = o.GameFilterEnabled.Get()
	}
	if o.ProducerFilterEnabled.IsSet() {
		toSerialize["producer_filter_enabled"] = o.ProducerFilterEnabled.Get()
	}
	if o.WebhookEnabled.IsSet() {
		toSerialize["webhook_enabled"] = o.WebhookEnabled.Get()
	}
	if o.IsActive.IsSet() {
		toSerialize["is_active"] = o.IsActive.Get()
	}
	if o.IsFeatured.IsSet() {
		toSerialize["is_featured"] = o.IsFeatured.Get()
	}
	return toSerialize, nil
}

type NullableUpdateAPromotionRequest struct {
	value *UpdateAPromotionRequest
	isSet bool
}

func (v NullableUpdateAPromotionRequest) Get() *UpdateAPromotionRequest {
	return v.value
}

func (v *NullableUpdateAPromotionRequest) Set(val *UpdateAPromotionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAPromotionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAPromotionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAPromotionRequest(val *UpdateAPromotionRequest) *NullableUpdateAPromotionRequest {
	return &NullableUpdateAPromotionRequest{value: val, isSet: true}
}

func (v NullableUpdateAPromotionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAPromotionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


