/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetSessionStatus200ResponseDataGame type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSessionStatus200ResponseDataGame{}

// GetSessionStatus200ResponseDataGame struct for GetSessionStatus200ResponseDataGame
type GetSessionStatus200ResponseDataGame struct {
	Id *int32 `json:"id,omitempty"`
	Title *string `json:"title,omitempty"`
}

// NewGetSessionStatus200ResponseDataGame instantiates a new GetSessionStatus200ResponseDataGame object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSessionStatus200ResponseDataGame() *GetSessionStatus200ResponseDataGame {
	this := GetSessionStatus200ResponseDataGame{}
	return &this
}

// NewGetSessionStatus200ResponseDataGameWithDefaults instantiates a new GetSessionStatus200ResponseDataGame object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSessionStatus200ResponseDataGameWithDefaults() *GetSessionStatus200ResponseDataGame {
	this := GetSessionStatus200ResponseDataGame{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *GetSessionStatus200ResponseDataGame) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSessionStatus200ResponseDataGame) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *GetSessionStatus200ResponseDataGame) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *GetSessionStatus200ResponseDataGame) SetId(v int32) {
	o.Id = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetSessionStatus200ResponseDataGame) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSessionStatus200ResponseDataGame) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetSessionStatus200ResponseDataGame) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetSessionStatus200ResponseDataGame) SetTitle(v string) {
	o.Title = &v
}

func (o GetSessionStatus200ResponseDataGame) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSessionStatus200ResponseDataGame) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	return toSerialize, nil
}

type NullableGetSessionStatus200ResponseDataGame struct {
	value *GetSessionStatus200ResponseDataGame
	isSet bool
}

func (v NullableGetSessionStatus200ResponseDataGame) Get() *GetSessionStatus200ResponseDataGame {
	return v.value
}

func (v *NullableGetSessionStatus200ResponseDataGame) Set(val *GetSessionStatus200ResponseDataGame) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSessionStatus200ResponseDataGame) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSessionStatus200ResponseDataGame) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSessionStatus200ResponseDataGame(val *GetSessionStatus200ResponseDataGame) *NullableGetSessionStatus200ResponseDataGame {
	return &NullableGetSessionStatus200ResponseDataGame{value: val, isSet: true}
}

func (v NullableGetSessionStatus200ResponseDataGame) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSessionStatus200ResponseDataGame) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


