/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the RegenerateDomainToken200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegenerateDomainToken200ResponseData{}

// RegenerateDomainToken200ResponseData struct for RegenerateDomainToken200ResponseData
type RegenerateDomainToken200ResponseData struct {
	DomainToken *string `json:"domain_token,omitempty"`
}

// NewRegenerateDomainToken200ResponseData instantiates a new RegenerateDomainToken200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegenerateDomainToken200ResponseData() *RegenerateDomainToken200ResponseData {
	this := RegenerateDomainToken200ResponseData{}
	return &this
}

// NewRegenerateDomainToken200ResponseDataWithDefaults instantiates a new RegenerateDomainToken200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegenerateDomainToken200ResponseDataWithDefaults() *RegenerateDomainToken200ResponseData {
	this := RegenerateDomainToken200ResponseData{}
	return &this
}

// GetDomainToken returns the DomainToken field value if set, zero value otherwise.
func (o *RegenerateDomainToken200ResponseData) GetDomainToken() string {
	if o == nil || IsNil(o.DomainToken) {
		var ret string
		return ret
	}
	return *o.DomainToken
}

// GetDomainTokenOk returns a tuple with the DomainToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegenerateDomainToken200ResponseData) GetDomainTokenOk() (*string, bool) {
	if o == nil || IsNil(o.DomainToken) {
		return nil, false
	}
	return o.DomainToken, true
}

// HasDomainToken returns a boolean if a field has been set.
func (o *RegenerateDomainToken200ResponseData) HasDomainToken() bool {
	if o != nil && !IsNil(o.DomainToken) {
		return true
	}

	return false
}

// SetDomainToken gets a reference to the given string and assigns it to the DomainToken field.
func (o *RegenerateDomainToken200ResponseData) SetDomainToken(v string) {
	o.DomainToken = &v
}

func (o RegenerateDomainToken200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegenerateDomainToken200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DomainToken) {
		toSerialize["domain_token"] = o.DomainToken
	}
	return toSerialize, nil
}

type NullableRegenerateDomainToken200ResponseData struct {
	value *RegenerateDomainToken200ResponseData
	isSet bool
}

func (v NullableRegenerateDomainToken200ResponseData) Get() *RegenerateDomainToken200ResponseData {
	return v.value
}

func (v *NullableRegenerateDomainToken200ResponseData) Set(val *RegenerateDomainToken200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableRegenerateDomainToken200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableRegenerateDomainToken200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegenerateDomainToken200ResponseData(val *RegenerateDomainToken200ResponseData) *NullableRegenerateDomainToken200ResponseData {
	return &NullableRegenerateDomainToken200ResponseData{value: val, isSet: true}
}

func (v NullableRegenerateDomainToken200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegenerateDomainToken200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


