/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetApiV1TransactionExportsExportIdDownload500Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetApiV1TransactionExportsExportIdDownload500Response{}

// GetApiV1TransactionExportsExportIdDownload500Response struct for GetApiV1TransactionExportsExportIdDownload500Response
type GetApiV1TransactionExportsExportIdDownload500Response struct {
	Message *string `json:"message,omitempty"`
}

// NewGetApiV1TransactionExportsExportIdDownload500Response instantiates a new GetApiV1TransactionExportsExportIdDownload500Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetApiV1TransactionExportsExportIdDownload500Response() *GetApiV1TransactionExportsExportIdDownload500Response {
	this := GetApiV1TransactionExportsExportIdDownload500Response{}
	return &this
}

// NewGetApiV1TransactionExportsExportIdDownload500ResponseWithDefaults instantiates a new GetApiV1TransactionExportsExportIdDownload500Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetApiV1TransactionExportsExportIdDownload500ResponseWithDefaults() *GetApiV1TransactionExportsExportIdDownload500Response {
	this := GetApiV1TransactionExportsExportIdDownload500Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetApiV1TransactionExportsExportIdDownload500Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetApiV1TransactionExportsExportIdDownload500Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetApiV1TransactionExportsExportIdDownload500Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetApiV1TransactionExportsExportIdDownload500Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetApiV1TransactionExportsExportIdDownload500Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetApiV1TransactionExportsExportIdDownload500Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetApiV1TransactionExportsExportIdDownload500Response struct {
	value *GetApiV1TransactionExportsExportIdDownload500Response
	isSet bool
}

func (v NullableGetApiV1TransactionExportsExportIdDownload500Response) Get() *GetApiV1TransactionExportsExportIdDownload500Response {
	return v.value
}

func (v *NullableGetApiV1TransactionExportsExportIdDownload500Response) Set(val *GetApiV1TransactionExportsExportIdDownload500Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetApiV1TransactionExportsExportIdDownload500Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetApiV1TransactionExportsExportIdDownload500Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetApiV1TransactionExportsExportIdDownload500Response(val *GetApiV1TransactionExportsExportIdDownload500Response) *NullableGetApiV1TransactionExportsExportIdDownload500Response {
	return &NullableGetApiV1TransactionExportsExportIdDownload500Response{value: val, isSet: true}
}

func (v NullableGetApiV1TransactionExportsExportIdDownload500Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetApiV1TransactionExportsExportIdDownload500Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


