/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetMultiSessionStatus404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMultiSessionStatus404Response{}

// GetMultiSessionStatus404Response struct for GetMultiSessionStatus404Response
type GetMultiSessionStatus404Response struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetMultiSessionStatus404Response instantiates a new GetMultiSessionStatus404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMultiSessionStatus404Response() *GetMultiSessionStatus404Response {
	this := GetMultiSessionStatus404Response{}
	return &this
}

// NewGetMultiSessionStatus404ResponseWithDefaults instantiates a new GetMultiSessionStatus404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMultiSessionStatus404ResponseWithDefaults() *GetMultiSessionStatus404Response {
	this := GetMultiSessionStatus404Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetMultiSessionStatus404Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMultiSessionStatus404Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetMultiSessionStatus404Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetMultiSessionStatus404Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetMultiSessionStatus404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMultiSessionStatus404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetMultiSessionStatus404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetMultiSessionStatus404Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetMultiSessionStatus404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMultiSessionStatus404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetMultiSessionStatus404Response struct {
	value *GetMultiSessionStatus404Response
	isSet bool
}

func (v NullableGetMultiSessionStatus404Response) Get() *GetMultiSessionStatus404Response {
	return v.value
}

func (v *NullableGetMultiSessionStatus404Response) Set(val *GetMultiSessionStatus404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMultiSessionStatus404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMultiSessionStatus404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMultiSessionStatus404Response(val *GetMultiSessionStatus404Response) *NullableGetMultiSessionStatus404Response {
	return &NullableGetMultiSessionStatus404Response{value: val, isSet: true}
}

func (v NullableGetMultiSessionStatus404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMultiSessionStatus404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


