/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfigureLiveModeSettingsForAPoolRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureLiveModeSettingsForAPoolRequest{}

// ConfigureLiveModeSettingsForAPoolRequest struct for ConfigureLiveModeSettingsForAPoolRequest
type ConfigureLiveModeSettingsForAPoolRequest struct {
	// 
	IsLiveMode bool `json:"is_live_mode"`
	// Must be at least 10. Must not be greater than 300.
	LiveModeWindowSeconds *int32 `json:"live_mode_window_seconds,omitempty"`
}

type _ConfigureLiveModeSettingsForAPoolRequest ConfigureLiveModeSettingsForAPoolRequest

// NewConfigureLiveModeSettingsForAPoolRequest instantiates a new ConfigureLiveModeSettingsForAPoolRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureLiveModeSettingsForAPoolRequest(isLiveMode bool) *ConfigureLiveModeSettingsForAPoolRequest {
	this := ConfigureLiveModeSettingsForAPoolRequest{}
	this.IsLiveMode = isLiveMode
	return &this
}

// NewConfigureLiveModeSettingsForAPoolRequestWithDefaults instantiates a new ConfigureLiveModeSettingsForAPoolRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureLiveModeSettingsForAPoolRequestWithDefaults() *ConfigureLiveModeSettingsForAPoolRequest {
	this := ConfigureLiveModeSettingsForAPoolRequest{}
	return &this
}

// GetIsLiveMode returns the IsLiveMode field value
func (o *ConfigureLiveModeSettingsForAPoolRequest) GetIsLiveMode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsLiveMode
}

// GetIsLiveModeOk returns a tuple with the IsLiveMode field value
// and a boolean to check if the value has been set.
func (o *ConfigureLiveModeSettingsForAPoolRequest) GetIsLiveModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsLiveMode, true
}

// SetIsLiveMode sets field value
func (o *ConfigureLiveModeSettingsForAPoolRequest) SetIsLiveMode(v bool) {
	o.IsLiveMode = v
}

// GetLiveModeWindowSeconds returns the LiveModeWindowSeconds field value if set, zero value otherwise.
func (o *ConfigureLiveModeSettingsForAPoolRequest) GetLiveModeWindowSeconds() int32 {
	if o == nil || IsNil(o.LiveModeWindowSeconds) {
		var ret int32
		return ret
	}
	return *o.LiveModeWindowSeconds
}

// GetLiveModeWindowSecondsOk returns a tuple with the LiveModeWindowSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureLiveModeSettingsForAPoolRequest) GetLiveModeWindowSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.LiveModeWindowSeconds) {
		return nil, false
	}
	return o.LiveModeWindowSeconds, true
}

// HasLiveModeWindowSeconds returns a boolean if a field has been set.
func (o *ConfigureLiveModeSettingsForAPoolRequest) HasLiveModeWindowSeconds() bool {
	if o != nil && !IsNil(o.LiveModeWindowSeconds) {
		return true
	}

	return false
}

// SetLiveModeWindowSeconds gets a reference to the given int32 and assigns it to the LiveModeWindowSeconds field.
func (o *ConfigureLiveModeSettingsForAPoolRequest) SetLiveModeWindowSeconds(v int32) {
	o.LiveModeWindowSeconds = &v
}

func (o ConfigureLiveModeSettingsForAPoolRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureLiveModeSettingsForAPoolRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["is_live_mode"] = o.IsLiveMode
	if !IsNil(o.LiveModeWindowSeconds) {
		toSerialize["live_mode_window_seconds"] = o.LiveModeWindowSeconds
	}
	return toSerialize, nil
}

func (o *ConfigureLiveModeSettingsForAPoolRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"is_live_mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfigureLiveModeSettingsForAPoolRequest := _ConfigureLiveModeSettingsForAPoolRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfigureLiveModeSettingsForAPoolRequest)

	if err != nil {
		return err
	}

	*o = ConfigureLiveModeSettingsForAPoolRequest(varConfigureLiveModeSettingsForAPoolRequest)

	return err
}

type NullableConfigureLiveModeSettingsForAPoolRequest struct {
	value *ConfigureLiveModeSettingsForAPoolRequest
	isSet bool
}

func (v NullableConfigureLiveModeSettingsForAPoolRequest) Get() *ConfigureLiveModeSettingsForAPoolRequest {
	return v.value
}

func (v *NullableConfigureLiveModeSettingsForAPoolRequest) Set(val *ConfigureLiveModeSettingsForAPoolRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureLiveModeSettingsForAPoolRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureLiveModeSettingsForAPoolRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureLiveModeSettingsForAPoolRequest(val *ConfigureLiveModeSettingsForAPoolRequest) *NullableConfigureLiveModeSettingsForAPoolRequest {
	return &NullableConfigureLiveModeSettingsForAPoolRequest{value: val, isSet: true}
}

func (v NullableConfigureLiveModeSettingsForAPoolRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureLiveModeSettingsForAPoolRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


