/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the CancelAStandaloneFreespin409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CancelAStandaloneFreespin409Response{}

// CancelAStandaloneFreespin409Response struct for CancelAStandaloneFreespin409Response
type CancelAStandaloneFreespin409Response struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCancelAStandaloneFreespin409Response instantiates a new CancelAStandaloneFreespin409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCancelAStandaloneFreespin409Response() *CancelAStandaloneFreespin409Response {
	this := CancelAStandaloneFreespin409Response{}
	return &this
}

// NewCancelAStandaloneFreespin409ResponseWithDefaults instantiates a new CancelAStandaloneFreespin409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCancelAStandaloneFreespin409ResponseWithDefaults() *CancelAStandaloneFreespin409Response {
	this := CancelAStandaloneFreespin409Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin409Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin409Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin409Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CancelAStandaloneFreespin409Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CancelAStandaloneFreespin409Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CancelAStandaloneFreespin409Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CancelAStandaloneFreespin409Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CancelAStandaloneFreespin409Response) SetMessage(v string) {
	o.Message = &v
}

func (o CancelAStandaloneFreespin409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CancelAStandaloneFreespin409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCancelAStandaloneFreespin409Response struct {
	value *CancelAStandaloneFreespin409Response
	isSet bool
}

func (v NullableCancelAStandaloneFreespin409Response) Get() *CancelAStandaloneFreespin409Response {
	return v.value
}

func (v *NullableCancelAStandaloneFreespin409Response) Set(val *CancelAStandaloneFreespin409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCancelAStandaloneFreespin409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCancelAStandaloneFreespin409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCancelAStandaloneFreespin409Response(val *CancelAStandaloneFreespin409Response) *NullableCancelAStandaloneFreespin409Response {
	return &NullableCancelAStandaloneFreespin409Response{value: val, isSet: true}
}

func (v NullableCancelAStandaloneFreespin409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCancelAStandaloneFreespin409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


