/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StartAMultiSessionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartAMultiSessionRequest{}

// StartAMultiSessionRequest struct for StartAMultiSessionRequest
type StartAMultiSessionRequest struct {
	// Player's ID in your system.
	PlayerId string `json:"player_id"`
	// Three-letter currency code (ISO 4217).
	Currency string `json:"currency"`
	// Two-letter country code (ISO 3166-1 alpha-2).
	CountryCode string `json:"country_code"`
	// Player's IP address.
	IpAddress string `json:"ip_address"`
	// optional Specific game IDs to include. If not provided, picks random games from each available provider.
	GameIds []string `json:"game_ids,omitempty"`
	// optional Player's language preference (ISO 639-1).
	Locale NullableString `json:"locale,omitempty"`
	// optional Device type: desktop, mobile, tablet.
	Device NullableString `json:"device,omitempty"`
}

type _StartAMultiSessionRequest StartAMultiSessionRequest

// NewStartAMultiSessionRequest instantiates a new StartAMultiSessionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartAMultiSessionRequest(playerId string, currency string, countryCode string, ipAddress string) *StartAMultiSessionRequest {
	this := StartAMultiSessionRequest{}
	this.PlayerId = playerId
	this.Currency = currency
	this.CountryCode = countryCode
	this.IpAddress = ipAddress
	return &this
}

// NewStartAMultiSessionRequestWithDefaults instantiates a new StartAMultiSessionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartAMultiSessionRequestWithDefaults() *StartAMultiSessionRequest {
	this := StartAMultiSessionRequest{}
	return &this
}

// GetPlayerId returns the PlayerId field value
func (o *StartAMultiSessionRequest) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *StartAMultiSessionRequest) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *StartAMultiSessionRequest) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetCurrency returns the Currency field value
func (o *StartAMultiSessionRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *StartAMultiSessionRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *StartAMultiSessionRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetCountryCode returns the CountryCode field value
func (o *StartAMultiSessionRequest) GetCountryCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value
// and a boolean to check if the value has been set.
func (o *StartAMultiSessionRequest) GetCountryCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CountryCode, true
}

// SetCountryCode sets field value
func (o *StartAMultiSessionRequest) SetCountryCode(v string) {
	o.CountryCode = v
}

// GetIpAddress returns the IpAddress field value
func (o *StartAMultiSessionRequest) GetIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IpAddress
}

// GetIpAddressOk returns a tuple with the IpAddress field value
// and a boolean to check if the value has been set.
func (o *StartAMultiSessionRequest) GetIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IpAddress, true
}

// SetIpAddress sets field value
func (o *StartAMultiSessionRequest) SetIpAddress(v string) {
	o.IpAddress = v
}

// GetGameIds returns the GameIds field value if set, zero value otherwise.
func (o *StartAMultiSessionRequest) GetGameIds() []string {
	if o == nil || IsNil(o.GameIds) {
		var ret []string
		return ret
	}
	return o.GameIds
}

// GetGameIdsOk returns a tuple with the GameIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartAMultiSessionRequest) GetGameIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.GameIds) {
		return nil, false
	}
	return o.GameIds, true
}

// HasGameIds returns a boolean if a field has been set.
func (o *StartAMultiSessionRequest) HasGameIds() bool {
	if o != nil && !IsNil(o.GameIds) {
		return true
	}

	return false
}

// SetGameIds gets a reference to the given []string and assigns it to the GameIds field.
func (o *StartAMultiSessionRequest) SetGameIds(v []string) {
	o.GameIds = v
}

// GetLocale returns the Locale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAMultiSessionRequest) GetLocale() string {
	if o == nil || IsNil(o.Locale.Get()) {
		var ret string
		return ret
	}
	return *o.Locale.Get()
}

// GetLocaleOk returns a tuple with the Locale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAMultiSessionRequest) GetLocaleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Locale.Get(), o.Locale.IsSet()
}

// HasLocale returns a boolean if a field has been set.
func (o *StartAMultiSessionRequest) HasLocale() bool {
	if o != nil && o.Locale.IsSet() {
		return true
	}

	return false
}

// SetLocale gets a reference to the given NullableString and assigns it to the Locale field.
func (o *StartAMultiSessionRequest) SetLocale(v string) {
	o.Locale.Set(&v)
}
// SetLocaleNil sets the value for Locale to be an explicit nil
func (o *StartAMultiSessionRequest) SetLocaleNil() {
	o.Locale.Set(nil)
}

// UnsetLocale ensures that no value is present for Locale, not even an explicit nil
func (o *StartAMultiSessionRequest) UnsetLocale() {
	o.Locale.Unset()
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *StartAMultiSessionRequest) GetDevice() string {
	if o == nil || IsNil(o.Device.Get()) {
		var ret string
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *StartAMultiSessionRequest) GetDeviceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *StartAMultiSessionRequest) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableString and assigns it to the Device field.
func (o *StartAMultiSessionRequest) SetDevice(v string) {
	o.Device.Set(&v)
}
// SetDeviceNil sets the value for Device to be an explicit nil
func (o *StartAMultiSessionRequest) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *StartAMultiSessionRequest) UnsetDevice() {
	o.Device.Unset()
}

func (o StartAMultiSessionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartAMultiSessionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["player_id"] = o.PlayerId
	toSerialize["currency"] = o.Currency
	toSerialize["country_code"] = o.CountryCode
	toSerialize["ip_address"] = o.IpAddress
	if !IsNil(o.GameIds) {
		toSerialize["game_ids"] = o.GameIds
	}
	if o.Locale.IsSet() {
		toSerialize["locale"] = o.Locale.Get()
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	return toSerialize, nil
}

func (o *StartAMultiSessionRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"player_id",
		"currency",
		"country_code",
		"ip_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStartAMultiSessionRequest := _StartAMultiSessionRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStartAMultiSessionRequest)

	if err != nil {
		return err
	}

	*o = StartAMultiSessionRequest(varStartAMultiSessionRequest)

	return err
}

type NullableStartAMultiSessionRequest struct {
	value *StartAMultiSessionRequest
	isSet bool
}

func (v NullableStartAMultiSessionRequest) Get() *StartAMultiSessionRequest {
	return v.value
}

func (v *NullableStartAMultiSessionRequest) Set(val *StartAMultiSessionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableStartAMultiSessionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableStartAMultiSessionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartAMultiSessionRequest(val *StartAMultiSessionRequest) *NullableStartAMultiSessionRequest {
	return &NullableStartAMultiSessionRequest{value: val, isSet: true}
}

func (v NullableStartAMultiSessionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartAMultiSessionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


