/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListGames200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListGames200ResponseMeta{}

// ListGames200ResponseMeta struct for ListGames200ResponseMeta
type ListGames200ResponseMeta struct {
	Total *int32 `json:"total,omitempty"`
}

// NewListGames200ResponseMeta instantiates a new ListGames200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListGames200ResponseMeta() *ListGames200ResponseMeta {
	this := ListGames200ResponseMeta{}
	return &this
}

// NewListGames200ResponseMetaWithDefaults instantiates a new ListGames200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListGames200ResponseMetaWithDefaults() *ListGames200ResponseMeta {
	this := ListGames200ResponseMeta{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ListGames200ResponseMeta) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListGames200ResponseMeta) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ListGames200ResponseMeta) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *ListGames200ResponseMeta) SetTotal(v int32) {
	o.Total = &v
}

func (o ListGames200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListGames200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableListGames200ResponseMeta struct {
	value *ListGames200ResponseMeta
	isSet bool
}

func (v NullableListGames200ResponseMeta) Get() *ListGames200ResponseMeta {
	return v.value
}

func (v *NullableListGames200ResponseMeta) Set(val *ListGames200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableListGames200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableListGames200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListGames200ResponseMeta(val *ListGames200ResponseMeta) *NullableListGames200ResponseMeta {
	return &NullableListGames200ResponseMeta{value: val, isSet: true}
}

func (v NullableListGames200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListGames200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


