/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the UpdateDomainSettings200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateDomainSettings200Response{}

// UpdateDomainSettings200Response struct for UpdateDomainSettings200Response
type UpdateDomainSettings200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *UpdateDomainSettings200ResponseData `json:"data,omitempty"`
}

// NewUpdateDomainSettings200Response instantiates a new UpdateDomainSettings200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateDomainSettings200Response() *UpdateDomainSettings200Response {
	this := UpdateDomainSettings200Response{}
	return &this
}

// NewUpdateDomainSettings200ResponseWithDefaults instantiates a new UpdateDomainSettings200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateDomainSettings200ResponseWithDefaults() *UpdateDomainSettings200Response {
	this := UpdateDomainSettings200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *UpdateDomainSettings200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainSettings200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *UpdateDomainSettings200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *UpdateDomainSettings200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UpdateDomainSettings200Response) GetData() UpdateDomainSettings200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret UpdateDomainSettings200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateDomainSettings200Response) GetDataOk() (*UpdateDomainSettings200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UpdateDomainSettings200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given UpdateDomainSettings200ResponseData and assigns it to the Data field.
func (o *UpdateDomainSettings200Response) SetData(v UpdateDomainSettings200ResponseData) {
	o.Data = &v
}

func (o UpdateDomainSettings200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateDomainSettings200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableUpdateDomainSettings200Response struct {
	value *UpdateDomainSettings200Response
	isSet bool
}

func (v NullableUpdateDomainSettings200Response) Get() *UpdateDomainSettings200Response {
	return v.value
}

func (v *NullableUpdateDomainSettings200Response) Set(val *UpdateDomainSettings200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateDomainSettings200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateDomainSettings200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateDomainSettings200Response(val *UpdateDomainSettings200Response) *NullableUpdateDomainSettings200Response {
	return &NullableUpdateDomainSettings200Response{value: val, isSet: true}
}

func (v NullableUpdateDomainSettings200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateDomainSettings200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


