/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner{}

// ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner struct for ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner
type ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner struct {
	// This field is required when <code>prize_tiers</code> is present. Must be at least 1.
	Tier *int32 `json:"tier,omitempty"`
	// This field is required when <code>prize_tiers</code> is present. Must be at least 1.
	WinnerCount *int32 `json:"winner_count,omitempty"`
	// This field is required when <code>prize_tiers</code> is present. Must be at least 0.01. Must not be greater than 100.
	Percentage *float32 `json:"percentage,omitempty"`
}

// NewConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner instantiates a new ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner() *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner {
	this := ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner{}
	return &this
}

// NewConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInnerWithDefaults instantiates a new ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInnerWithDefaults() *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner {
	this := ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner{}
	return &this
}

// GetTier returns the Tier field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) GetTier() int32 {
	if o == nil || IsNil(o.Tier) {
		var ret int32
		return ret
	}
	return *o.Tier
}

// GetTierOk returns a tuple with the Tier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) GetTierOk() (*int32, bool) {
	if o == nil || IsNil(o.Tier) {
		return nil, false
	}
	return o.Tier, true
}

// HasTier returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) HasTier() bool {
	if o != nil && !IsNil(o.Tier) {
		return true
	}

	return false
}

// SetTier gets a reference to the given int32 and assigns it to the Tier field.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) SetTier(v int32) {
	o.Tier = &v
}

// GetWinnerCount returns the WinnerCount field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) GetWinnerCount() int32 {
	if o == nil || IsNil(o.WinnerCount) {
		var ret int32
		return ret
	}
	return *o.WinnerCount
}

// GetWinnerCountOk returns a tuple with the WinnerCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) GetWinnerCountOk() (*int32, bool) {
	if o == nil || IsNil(o.WinnerCount) {
		return nil, false
	}
	return o.WinnerCount, true
}

// HasWinnerCount returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) HasWinnerCount() bool {
	if o != nil && !IsNil(o.WinnerCount) {
		return true
	}

	return false
}

// SetWinnerCount gets a reference to the given int32 and assigns it to the WinnerCount field.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) SetWinnerCount(v int32) {
	o.WinnerCount = &v
}

// GetPercentage returns the Percentage field value if set, zero value otherwise.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) GetPercentage() float32 {
	if o == nil || IsNil(o.Percentage) {
		var ret float32
		return ret
	}
	return *o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) GetPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.Percentage) {
		return nil, false
	}
	return o.Percentage, true
}

// HasPercentage returns a boolean if a field has been set.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) HasPercentage() bool {
	if o != nil && !IsNil(o.Percentage) {
		return true
	}

	return false
}

// SetPercentage gets a reference to the given float32 and assigns it to the Percentage field.
func (o *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) SetPercentage(v float32) {
	o.Percentage = &v
}

func (o ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Tier) {
		toSerialize["tier"] = o.Tier
	}
	if !IsNil(o.WinnerCount) {
		toSerialize["winner_count"] = o.WinnerCount
	}
	if !IsNil(o.Percentage) {
		toSerialize["percentage"] = o.Percentage
	}
	return toSerialize, nil
}

type NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner struct {
	value *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner
	isSet bool
}

func (v NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) Get() *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner {
	return v.value
}

func (v *NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) Set(val *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner(val *ConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) *NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner {
	return &NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner{value: val, isSet: true}
}

func (v NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigureJackpotSettingsForTheOperatorRequestPrizeTiersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


