/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ListRegisteredDomains200ResponseDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRegisteredDomains200ResponseDataInner{}

// ListRegisteredDomains200ResponseDataInner struct for ListRegisteredDomains200ResponseDataInner
type ListRegisteredDomains200ResponseDataInner struct {
	Id *int32 `json:"id,omitempty"`
	Domain *string `json:"domain,omitempty"`
	DomainToken *string `json:"domain_token,omitempty"`
	IsActive *bool `json:"is_active,omitempty"`
	AllowedWidgets []string `json:"allowed_widgets,omitempty"`
	TokensCount *int32 `json:"tokens_count,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
}

// NewListRegisteredDomains200ResponseDataInner instantiates a new ListRegisteredDomains200ResponseDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRegisteredDomains200ResponseDataInner() *ListRegisteredDomains200ResponseDataInner {
	this := ListRegisteredDomains200ResponseDataInner{}
	return &this
}

// NewListRegisteredDomains200ResponseDataInnerWithDefaults instantiates a new ListRegisteredDomains200ResponseDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRegisteredDomains200ResponseDataInnerWithDefaults() *ListRegisteredDomains200ResponseDataInner {
	this := ListRegisteredDomains200ResponseDataInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ListRegisteredDomains200ResponseDataInner) SetId(v int32) {
	o.Id = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *ListRegisteredDomains200ResponseDataInner) SetDomain(v string) {
	o.Domain = &v
}

// GetDomainToken returns the DomainToken field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetDomainToken() string {
	if o == nil || IsNil(o.DomainToken) {
		var ret string
		return ret
	}
	return *o.DomainToken
}

// GetDomainTokenOk returns a tuple with the DomainToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetDomainTokenOk() (*string, bool) {
	if o == nil || IsNil(o.DomainToken) {
		return nil, false
	}
	return o.DomainToken, true
}

// HasDomainToken returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasDomainToken() bool {
	if o != nil && !IsNil(o.DomainToken) {
		return true
	}

	return false
}

// SetDomainToken gets a reference to the given string and assigns it to the DomainToken field.
func (o *ListRegisteredDomains200ResponseDataInner) SetDomainToken(v string) {
	o.DomainToken = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *ListRegisteredDomains200ResponseDataInner) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetAllowedWidgets returns the AllowedWidgets field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetAllowedWidgets() []string {
	if o == nil || IsNil(o.AllowedWidgets) {
		var ret []string
		return ret
	}
	return o.AllowedWidgets
}

// GetAllowedWidgetsOk returns a tuple with the AllowedWidgets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetAllowedWidgetsOk() ([]string, bool) {
	if o == nil || IsNil(o.AllowedWidgets) {
		return nil, false
	}
	return o.AllowedWidgets, true
}

// HasAllowedWidgets returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasAllowedWidgets() bool {
	if o != nil && !IsNil(o.AllowedWidgets) {
		return true
	}

	return false
}

// SetAllowedWidgets gets a reference to the given []string and assigns it to the AllowedWidgets field.
func (o *ListRegisteredDomains200ResponseDataInner) SetAllowedWidgets(v []string) {
	o.AllowedWidgets = v
}

// GetTokensCount returns the TokensCount field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetTokensCount() int32 {
	if o == nil || IsNil(o.TokensCount) {
		var ret int32
		return ret
	}
	return *o.TokensCount
}

// GetTokensCountOk returns a tuple with the TokensCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetTokensCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TokensCount) {
		return nil, false
	}
	return o.TokensCount, true
}

// HasTokensCount returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasTokensCount() bool {
	if o != nil && !IsNil(o.TokensCount) {
		return true
	}

	return false
}

// SetTokensCount gets a reference to the given int32 and assigns it to the TokensCount field.
func (o *ListRegisteredDomains200ResponseDataInner) SetTokensCount(v int32) {
	o.TokensCount = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ListRegisteredDomains200ResponseDataInner) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListRegisteredDomains200ResponseDataInner) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ListRegisteredDomains200ResponseDataInner) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ListRegisteredDomains200ResponseDataInner) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

func (o ListRegisteredDomains200ResponseDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRegisteredDomains200ResponseDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.DomainToken) {
		toSerialize["domain_token"] = o.DomainToken
	}
	if !IsNil(o.IsActive) {
		toSerialize["is_active"] = o.IsActive
	}
	if !IsNil(o.AllowedWidgets) {
		toSerialize["allowed_widgets"] = o.AllowedWidgets
	}
	if !IsNil(o.TokensCount) {
		toSerialize["tokens_count"] = o.TokensCount
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	return toSerialize, nil
}

type NullableListRegisteredDomains200ResponseDataInner struct {
	value *ListRegisteredDomains200ResponseDataInner
	isSet bool
}

func (v NullableListRegisteredDomains200ResponseDataInner) Get() *ListRegisteredDomains200ResponseDataInner {
	return v.value
}

func (v *NullableListRegisteredDomains200ResponseDataInner) Set(val *ListRegisteredDomains200ResponseDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListRegisteredDomains200ResponseDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListRegisteredDomains200ResponseDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRegisteredDomains200ResponseDataInner(val *ListRegisteredDomains200ResponseDataInner) *NullableListRegisteredDomains200ResponseDataInner {
	return &NullableListRegisteredDomains200ResponseDataInner{value: val, isSet: true}
}

func (v NullableListRegisteredDomains200ResponseDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRegisteredDomains200ResponseDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


