/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the CreateAStandaloneFreespin403Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAStandaloneFreespin403Response{}

// CreateAStandaloneFreespin403Response struct for CreateAStandaloneFreespin403Response
type CreateAStandaloneFreespin403Response struct {
	Success *bool `json:"success,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCreateAStandaloneFreespin403Response instantiates a new CreateAStandaloneFreespin403Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAStandaloneFreespin403Response() *CreateAStandaloneFreespin403Response {
	this := CreateAStandaloneFreespin403Response{}
	return &this
}

// NewCreateAStandaloneFreespin403ResponseWithDefaults instantiates a new CreateAStandaloneFreespin403Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAStandaloneFreespin403ResponseWithDefaults() *CreateAStandaloneFreespin403Response {
	this := CreateAStandaloneFreespin403Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreateAStandaloneFreespin403Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespin403Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreateAStandaloneFreespin403Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CreateAStandaloneFreespin403Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateAStandaloneFreespin403Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAStandaloneFreespin403Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateAStandaloneFreespin403Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateAStandaloneFreespin403Response) SetMessage(v string) {
	o.Message = &v
}

func (o CreateAStandaloneFreespin403Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAStandaloneFreespin403Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateAStandaloneFreespin403Response struct {
	value *CreateAStandaloneFreespin403Response
	isSet bool
}

func (v NullableCreateAStandaloneFreespin403Response) Get() *CreateAStandaloneFreespin403Response {
	return v.value
}

func (v *NullableCreateAStandaloneFreespin403Response) Set(val *CreateAStandaloneFreespin403Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAStandaloneFreespin403Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAStandaloneFreespin403Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAStandaloneFreespin403Response(val *CreateAStandaloneFreespin403Response) *NullableCreateAStandaloneFreespin403Response {
	return &NullableCreateAStandaloneFreespin403Response{value: val, isSet: true}
}

func (v NullableCreateAStandaloneFreespin403Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAStandaloneFreespin403Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


