/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateATargetedPlayerConfigurationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateATargetedPlayerConfigurationRequest{}

// CreateATargetedPlayerConfigurationRequest struct for CreateATargetedPlayerConfigurationRequest
type CreateATargetedPlayerConfigurationRequest struct {
	// Must not be greater than 100 characters.
	PlayerId string `json:"player_id"`
	// 
	PoolType string `json:"pool_type"`
	// Must be 3 characters.
	Currency string `json:"currency"`
	// Must be at least 1.
	ThresholdAmount float32 `json:"threshold_amount"`
	// Must be at least 0.
	ThresholdVariance *float32 `json:"threshold_variance,omitempty"`
	// 
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}

type _CreateATargetedPlayerConfigurationRequest CreateATargetedPlayerConfigurationRequest

// NewCreateATargetedPlayerConfigurationRequest instantiates a new CreateATargetedPlayerConfigurationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateATargetedPlayerConfigurationRequest(playerId string, poolType string, currency string, thresholdAmount float32) *CreateATargetedPlayerConfigurationRequest {
	this := CreateATargetedPlayerConfigurationRequest{}
	this.PlayerId = playerId
	this.PoolType = poolType
	this.Currency = currency
	this.ThresholdAmount = thresholdAmount
	return &this
}

// NewCreateATargetedPlayerConfigurationRequestWithDefaults instantiates a new CreateATargetedPlayerConfigurationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateATargetedPlayerConfigurationRequestWithDefaults() *CreateATargetedPlayerConfigurationRequest {
	this := CreateATargetedPlayerConfigurationRequest{}
	return &this
}

// GetPlayerId returns the PlayerId field value
func (o *CreateATargetedPlayerConfigurationRequest) GetPlayerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlayerId
}

// GetPlayerIdOk returns a tuple with the PlayerId field value
// and a boolean to check if the value has been set.
func (o *CreateATargetedPlayerConfigurationRequest) GetPlayerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlayerId, true
}

// SetPlayerId sets field value
func (o *CreateATargetedPlayerConfigurationRequest) SetPlayerId(v string) {
	o.PlayerId = v
}

// GetPoolType returns the PoolType field value
func (o *CreateATargetedPlayerConfigurationRequest) GetPoolType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PoolType
}

// GetPoolTypeOk returns a tuple with the PoolType field value
// and a boolean to check if the value has been set.
func (o *CreateATargetedPlayerConfigurationRequest) GetPoolTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PoolType, true
}

// SetPoolType sets field value
func (o *CreateATargetedPlayerConfigurationRequest) SetPoolType(v string) {
	o.PoolType = v
}

// GetCurrency returns the Currency field value
func (o *CreateATargetedPlayerConfigurationRequest) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *CreateATargetedPlayerConfigurationRequest) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *CreateATargetedPlayerConfigurationRequest) SetCurrency(v string) {
	o.Currency = v
}

// GetThresholdAmount returns the ThresholdAmount field value
func (o *CreateATargetedPlayerConfigurationRequest) GetThresholdAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ThresholdAmount
}

// GetThresholdAmountOk returns a tuple with the ThresholdAmount field value
// and a boolean to check if the value has been set.
func (o *CreateATargetedPlayerConfigurationRequest) GetThresholdAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ThresholdAmount, true
}

// SetThresholdAmount sets field value
func (o *CreateATargetedPlayerConfigurationRequest) SetThresholdAmount(v float32) {
	o.ThresholdAmount = v
}

// GetThresholdVariance returns the ThresholdVariance field value if set, zero value otherwise.
func (o *CreateATargetedPlayerConfigurationRequest) GetThresholdVariance() float32 {
	if o == nil || IsNil(o.ThresholdVariance) {
		var ret float32
		return ret
	}
	return *o.ThresholdVariance
}

// GetThresholdVarianceOk returns a tuple with the ThresholdVariance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateATargetedPlayerConfigurationRequest) GetThresholdVarianceOk() (*float32, bool) {
	if o == nil || IsNil(o.ThresholdVariance) {
		return nil, false
	}
	return o.ThresholdVariance, true
}

// HasThresholdVariance returns a boolean if a field has been set.
func (o *CreateATargetedPlayerConfigurationRequest) HasThresholdVariance() bool {
	if o != nil && !IsNil(o.ThresholdVariance) {
		return true
	}

	return false
}

// SetThresholdVariance gets a reference to the given float32 and assigns it to the ThresholdVariance field.
func (o *CreateATargetedPlayerConfigurationRequest) SetThresholdVariance(v float32) {
	o.ThresholdVariance = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *CreateATargetedPlayerConfigurationRequest) GetMetadata() map[string]interface{} {
	if o == nil || IsNil(o.Metadata) {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateATargetedPlayerConfigurationRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *CreateATargetedPlayerConfigurationRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *CreateATargetedPlayerConfigurationRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

func (o CreateATargetedPlayerConfigurationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateATargetedPlayerConfigurationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["player_id"] = o.PlayerId
	toSerialize["pool_type"] = o.PoolType
	toSerialize["currency"] = o.Currency
	toSerialize["threshold_amount"] = o.ThresholdAmount
	if !IsNil(o.ThresholdVariance) {
		toSerialize["threshold_variance"] = o.ThresholdVariance
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	return toSerialize, nil
}

func (o *CreateATargetedPlayerConfigurationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"player_id",
		"pool_type",
		"currency",
		"threshold_amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateATargetedPlayerConfigurationRequest := _CreateATargetedPlayerConfigurationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateATargetedPlayerConfigurationRequest)

	if err != nil {
		return err
	}

	*o = CreateATargetedPlayerConfigurationRequest(varCreateATargetedPlayerConfigurationRequest)

	return err
}

type NullableCreateATargetedPlayerConfigurationRequest struct {
	value *CreateATargetedPlayerConfigurationRequest
	isSet bool
}

func (v NullableCreateATargetedPlayerConfigurationRequest) Get() *CreateATargetedPlayerConfigurationRequest {
	return v.value
}

func (v *NullableCreateATargetedPlayerConfigurationRequest) Set(val *CreateATargetedPlayerConfigurationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateATargetedPlayerConfigurationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateATargetedPlayerConfigurationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateATargetedPlayerConfigurationRequest(val *CreateATargetedPlayerConfigurationRequest) *NullableCreateATargetedPlayerConfigurationRequest {
	return &NullableCreateATargetedPlayerConfigurationRequest{value: val, isSet: true}
}

func (v NullableCreateATargetedPlayerConfigurationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateATargetedPlayerConfigurationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


