/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the ManageGamesForAPromotionRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageGamesForAPromotionRequest{}

// ManageGamesForAPromotionRequest struct for ManageGamesForAPromotionRequest
type ManageGamesForAPromotionRequest struct {
	// The <code>id</code> of an existing record in the games table.
	GameIds []int32 `json:"game_ids,omitempty"`
}

// NewManageGamesForAPromotionRequest instantiates a new ManageGamesForAPromotionRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageGamesForAPromotionRequest() *ManageGamesForAPromotionRequest {
	this := ManageGamesForAPromotionRequest{}
	return &this
}

// NewManageGamesForAPromotionRequestWithDefaults instantiates a new ManageGamesForAPromotionRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageGamesForAPromotionRequestWithDefaults() *ManageGamesForAPromotionRequest {
	this := ManageGamesForAPromotionRequest{}
	return &this
}

// GetGameIds returns the GameIds field value if set, zero value otherwise.
func (o *ManageGamesForAPromotionRequest) GetGameIds() []int32 {
	if o == nil || IsNil(o.GameIds) {
		var ret []int32
		return ret
	}
	return o.GameIds
}

// GetGameIdsOk returns a tuple with the GameIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageGamesForAPromotionRequest) GetGameIdsOk() ([]int32, bool) {
	if o == nil || IsNil(o.GameIds) {
		return nil, false
	}
	return o.GameIds, true
}

// HasGameIds returns a boolean if a field has been set.
func (o *ManageGamesForAPromotionRequest) HasGameIds() bool {
	if o != nil && !IsNil(o.GameIds) {
		return true
	}

	return false
}

// SetGameIds gets a reference to the given []int32 and assigns it to the GameIds field.
func (o *ManageGamesForAPromotionRequest) SetGameIds(v []int32) {
	o.GameIds = v
}

func (o ManageGamesForAPromotionRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageGamesForAPromotionRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GameIds) {
		toSerialize["game_ids"] = o.GameIds
	}
	return toSerialize, nil
}

type NullableManageGamesForAPromotionRequest struct {
	value *ManageGamesForAPromotionRequest
	isSet bool
}

func (v NullableManageGamesForAPromotionRequest) Get() *ManageGamesForAPromotionRequest {
	return v.value
}

func (v *NullableManageGamesForAPromotionRequest) Set(val *ManageGamesForAPromotionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableManageGamesForAPromotionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableManageGamesForAPromotionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageGamesForAPromotionRequest(val *ManageGamesForAPromotionRequest) *NullableManageGamesForAPromotionRequest {
	return &NullableManageGamesForAPromotionRequest{value: val, isSet: true}
}

func (v NullableManageGamesForAPromotionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageGamesForAPromotionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


