/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GenerateAWidgetToken201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GenerateAWidgetToken201Response{}

// GenerateAWidgetToken201Response struct for GenerateAWidgetToken201Response
type GenerateAWidgetToken201Response struct {
	Success *bool `json:"success,omitempty"`
	Data *GenerateAWidgetToken201ResponseData `json:"data,omitempty"`
}

// NewGenerateAWidgetToken201Response instantiates a new GenerateAWidgetToken201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGenerateAWidgetToken201Response() *GenerateAWidgetToken201Response {
	this := GenerateAWidgetToken201Response{}
	return &this
}

// NewGenerateAWidgetToken201ResponseWithDefaults instantiates a new GenerateAWidgetToken201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGenerateAWidgetToken201ResponseWithDefaults() *GenerateAWidgetToken201Response {
	this := GenerateAWidgetToken201Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GenerateAWidgetToken201Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateAWidgetToken201Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GenerateAWidgetToken201Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GenerateAWidgetToken201Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GenerateAWidgetToken201Response) GetData() GenerateAWidgetToken201ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GenerateAWidgetToken201ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GenerateAWidgetToken201Response) GetDataOk() (*GenerateAWidgetToken201ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GenerateAWidgetToken201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GenerateAWidgetToken201ResponseData and assigns it to the Data field.
func (o *GenerateAWidgetToken201Response) SetData(v GenerateAWidgetToken201ResponseData) {
	o.Data = &v
}

func (o GenerateAWidgetToken201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GenerateAWidgetToken201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGenerateAWidgetToken201Response struct {
	value *GenerateAWidgetToken201Response
	isSet bool
}

func (v NullableGenerateAWidgetToken201Response) Get() *GenerateAWidgetToken201Response {
	return v.value
}

func (v *NullableGenerateAWidgetToken201Response) Set(val *GenerateAWidgetToken201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGenerateAWidgetToken201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGenerateAWidgetToken201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGenerateAWidgetToken201Response(val *GenerateAWidgetToken201Response) *NullableGenerateAWidgetToken201Response {
	return &NullableGenerateAWidgetToken201Response{value: val, isSet: true}
}

func (v NullableGenerateAWidgetToken201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGenerateAWidgetToken201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


