/*
Game Aggregator API Documentation

Universal API for casino operators to access games from multiple providers through a single integration.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package iplaygamesapi

import (
	"encoding/json"
)

// checks if the GetTransactionHistory200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTransactionHistory200Response{}

// GetTransactionHistory200Response struct for GetTransactionHistory200Response
type GetTransactionHistory200Response struct {
	Success *bool `json:"success,omitempty"`
	Data []GetTransactionHistory200ResponseDataInner `json:"data,omitempty"`
	Meta *GetTransactionHistory200ResponseMeta `json:"meta,omitempty"`
}

// NewGetTransactionHistory200Response instantiates a new GetTransactionHistory200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTransactionHistory200Response() *GetTransactionHistory200Response {
	this := GetTransactionHistory200Response{}
	return &this
}

// NewGetTransactionHistory200ResponseWithDefaults instantiates a new GetTransactionHistory200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTransactionHistory200ResponseWithDefaults() *GetTransactionHistory200Response {
	this := GetTransactionHistory200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetTransactionHistory200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetTransactionHistory200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetTransactionHistory200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetTransactionHistory200Response) GetData() []GetTransactionHistory200ResponseDataInner {
	if o == nil || IsNil(o.Data) {
		var ret []GetTransactionHistory200ResponseDataInner
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200Response) GetDataOk() ([]GetTransactionHistory200ResponseDataInner, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetTransactionHistory200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []GetTransactionHistory200ResponseDataInner and assigns it to the Data field.
func (o *GetTransactionHistory200Response) SetData(v []GetTransactionHistory200ResponseDataInner) {
	o.Data = v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetTransactionHistory200Response) GetMeta() GetTransactionHistory200ResponseMeta {
	if o == nil || IsNil(o.Meta) {
		var ret GetTransactionHistory200ResponseMeta
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTransactionHistory200Response) GetMetaOk() (*GetTransactionHistory200ResponseMeta, bool) {
	if o == nil || IsNil(o.Meta) {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetTransactionHistory200Response) HasMeta() bool {
	if o != nil && !IsNil(o.Meta) {
		return true
	}

	return false
}

// SetMeta gets a reference to the given GetTransactionHistory200ResponseMeta and assigns it to the Meta field.
func (o *GetTransactionHistory200Response) SetMeta(v GetTransactionHistory200ResponseMeta) {
	o.Meta = &v
}

func (o GetTransactionHistory200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTransactionHistory200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Meta) {
		toSerialize["meta"] = o.Meta
	}
	return toSerialize, nil
}

type NullableGetTransactionHistory200Response struct {
	value *GetTransactionHistory200Response
	isSet bool
}

func (v NullableGetTransactionHistory200Response) Get() *GetTransactionHistory200Response {
	return v.value
}

func (v *NullableGetTransactionHistory200Response) Set(val *GetTransactionHistory200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTransactionHistory200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTransactionHistory200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTransactionHistory200Response(val *GetTransactionHistory200Response) *NullableGetTransactionHistory200Response {
	return &NullableGetTransactionHistory200Response{value: val, isSet: true}
}

func (v NullableGetTransactionHistory200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTransactionHistory200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


